#+TITLE: Introduction to Differential Equations

* Introduction

We are trying to determine an unknown function from prescribed information expressed in the form of an equation involving at least one of the derivatives of the unknown function.

Differential equations are classified under two main headings: ordinary (one variable) and partial (two or more variables).

Here is an example of an ODE:

$f'(x) = f(x)$

and a PDE:

$\frac{\partial^2 f(x, y)}{\partial x^2} + \frac{\partial^2 f(x, y)}{\partial y^2} = 0$

* Terminology and Notation

We shall begin our study with first order equations which can be solved for $y'$ and written as follows:

$y' = f(x, y)$

A differentiable function $y = Y(x)$ will be called a solution of above on an interval $I$ if the function $Y$ and its derivative $Y'$ satisfy the relation

$Y'(x) = f[x, Y(x)]$

for every $x \in I$.

The simplest case occurs when $f(x, y)$ is independent of $y$. In this case, our initial equation becomes

$y' = Q(x)$

where $Q$ is assumed to be a given function defined on some interval $I$. To solve the differential equation above means to find a primitive of $Q$.
If $Q$ is continuous and on the open interval $I$, then we can use the second fundamental theorem of calculus:

$y = \int Q(x) dx + C$

* A First-Order Differential Equation for the Exponential Function

** Theorem 8.1 | Existence-Uniqueness Theorem for $f'(x) = f(x)$

If $C$ is a given real number, then there is one and only one function $f$ which satisfies the differential equation

$f'(x) = f(x)$

for all real $x$ and which also satisfies the initial condition $f(x) = C$. This function is given by the formula

$f(x) = Ce^x$

* First-Order Linear Differential Equations

A differential equation of the form

$y' + P(x)y = Q(x)$

where $P, Q$ are given functions, is called a first-order linear differential equation. The terms involving the unknown function y and its derivative y' appear as a linear combination of y and y'.
The functions $P,Q$ are assumed to be continuous on some open interval $I$, and we seek all solutions $y$ defined on $I$.

First we consider the special case in which the right member, $Q(x)$ is identically 0. The equation

$y' + P(x)y = 0$

is called the *homogenous* or *reduced* equation corresponding to the above.

If y is nonzero on $I$, our homogenous equation is equivalent to

$\frac{y'}{y} = -P(x)$

** Theorem 8.2 | Existence-Uniqueness for $y' + P(x)y = 0$

Assume $P$ is continuous on an open interval $I$. Choose any point $a$ in $I$ and let $b$ be any real number. Then there is one and only one function $y = f(x)$ which satisfies the initial-value problem

$y' + P(x)y = 0$ with $f(a) = b$

on the interval $I$. This function is given by the formula

$f(x) = be^{-A(x)}$ where $A(x) = \int_a^x P(t) dt$

** Theorem 8.3 | Existence-Uniqueness for $y' + P(x)y = Q(x)$

Assume $P$ and $Q$ are continuous in the open interval $I$. Choose any point $a$ in $I$ and let $b$ be any real number. Then there is one and only one function $y = f(x)$ which satisfies the initial-value problem

$y' + P(x)y = Q(x)$ with $f(a) = b$

on the interval $I$. This function is given by the formula

$f(x) = be^{-A(x)} + e^{-A(x)} \int_a^x Q(t)e^{A(t)} dt$

where $A(x) = \int_a^x P(t) dt$

* Exercises

** Bernoulli Equation for Transforming a nonlinear ODE into a linear one

*The Bernoulli Equation*:
A differential equation of the form $y' + P(x)y = Q(x)y^n$ where $n \neq 0, 1$ is called a Bernoulli equation. This equation is nonlinear because of the presence of $y^n$.


* Introduction to Differential Equations

Starting the chapter over after a long break (~ 4 months)

* Introduction to Differential Equations

Starting the chapter over after another long break :/

*** Ricatti Equation

An equation of the form $y' + P(x)y + Q(x)y^2 = R(x)$ is called a *Ricatti Equation*

* Some physical problems leading to first-order linear differential equations

A handful of interesting examples: radioactive decay, falling body in resisting medium, a cooling problem, a dilution problem, electric circuits

* Linear Equations of Second Order with Constant Coefficients

** Form

$y'' + P_1(x)y' + P_2(x)y = R(x)$

is said to be a linear equation of second order, where $P_1, P_2$ are the coefficients of the equation

Here we only focus on situations where $P_1, P_2$ are constants. The general case is looked at in volume 2.

When $R(x) = 0$, we say the equation is homogenous

* Existence of Solutions of the Equation $y'' + by = 0$

** Theorem 8.4

Let y and u be two functions such that $y = u e^{-ax/2}$. Then, on the interval $(\pm \infty)$, y satisfies the differential equation $y'' + ay' + by = 0$ iff u satisfies the differential equation

$u'' + \frac{4b - a^2}{4} u = 0$

This theorem reduces the study of the equation $y'' + ay' + by = 0$ to the special case $y'' + by = 0$.

* Uniqueness Theorem for the Equation $y'' + by = 0$

** Theorem 8.5

Assume two functions f and g satisfy the differential equation $y'' + by = 0$ on $(\pm \infty)$. Assume also that f and g satisfy the initial conditions $f(0) = g(0)$ and $f'(0) = g'(0)$.

Then $f(x) = g(x)$ for all x

* Complete Solution of the Equation $y'' + by = 0$

** Theorem 8.6

Given a real number b, define two functions $u_1$ and $u_2$ on $(\pm \infty)$ as follows:

a. If b = 0, let $u_1(x) = 1$, $u_2(x) = x$
b. If b < 0, write $b = -k^2$, and define $u_1(x) = e^{kx}$, $u_2(x) = e^{-kx}$
c. if b > 0, write $b = k^2$ and define $u_1(x) = \cos kx$, $u_2(x) = \sin kx$

Then, every solution of the differential equation $y'' + by = 0$ on $(\pm \infty)$ has the form

$y = c_1 u_1(x) + c_2 u_2(x)$

where $c_1$ and $c_2$ are constants

* Complete Solution of the Equation $y'' + ay + by = 0$

The solution combines theorems 8.4 and 8.6 to obtain the following:

** Theorem 8.7
Let $d = a^2 - 4b$ be the discriminant of the linear differential equation $y'' + ay' + by = 0$. Then every solution of this equation on $(\pm \infty)$ has the form

$y = e^{-ax/2}[c_1 u_1(x) + c^2 u_2(x)]$

where $c_1$, $c^2$ are constants, and the functions $u_1$ and $u_2$ are determined according to the algebraic sign of the discriminant as follows:

a. If d = 0, then $u_1(x) = 1$ and $u_2(x) = x$
b. If d > 0, then $u_1(x) = e^{kx}$ and $u_2(x) = e^{-kx}$, where $k = \frac{1}{2}\sqrt{d}$
c. If d < 0, then $u_1(x) = \cos kx$ and $u_2(x) = \sin kx$ where $k = \frac{1}{2}\sqrt{-d}$

Note: In case b, where the discriminant d is positive, the solution y is a linear combination of two exponential functions:

$y = e^{-ax/2}(c_1 e^{kx} + c_2 e^{-kx}) = c_1 e^{r_1 x} + c_2 e^{r_2 x}$

where

$r_1 = - \frac{a}{2} + k = \frac{-a + \sqrt{d}}{2}$ , $r_2 = - \frac{a}{2} - k = \frac{-a - \sqrt{d}}{2}$

These two numbers $r_1, r_2$ has the sum $r_1 + r_2 = -a$ and product $r_1 r_2 = \frac{1}{4}(a^2 - d) = b$

Therefore, they are roots of the quadratic equation $r^2 + ar + b = 0$

This is called the characteristic equation associated with the differential equation

$y'' + ay' + by = 0$


** The Wronskian

Given two functions $u_1, u_2$, the function $W$ defined by $W(x) = u_1(x) u_2'(x) - u_2(x) u_1'(x)$ is called their *Wronskian*, after J.M.H. Wronski.

* Nonhomogenous Linear Equations of Second Order with Constant Coefficients

** Nonhomogenous Linear Equation of Second Order

$y'' + ay' + by = R$

** General Solution

$y = c_1 v_1 + c_2 v_2 + y_1$

where $c_1, c_2$ are arbitrary constants and $y_1$ is one particular solution of the nonhomogenous equation

** Theorem 8.8

If $y_1$ is a particular solution of the nonhomogenous equation $L(y) = R$, the general solution is obtained by adding to $y_1$ the general solution of the corresponding homogenous equation $L(y) = 0$

** General Solution to the Homogenous Equation $L(y) = 0$

$y = c_1 v_1 + c_2 v_2$ where $v_1(x) = e^{-ax/2}u_1(x)$ and $v_2(x) = e^{-ax/2}u_2(x)$

** Theorem 8.9

Let $v_1, v_2$ be the solutions of the equation $L(y) = 0$ given by above, where $L(y) = y'' + ay' + by$. Let $W$ denote the Wronskian of $v_1$ and $v_2$. Then the nonhomogenous equation $L(y) = R$ has a particular solution $y_1$ given by the formula

$y_1(x) = t_1(x)v_1(x) + t_2(x)v_2(x)$

where

$t_1(x) = - \int v_2(x) \frac{R(x)}{W(x)} dx$ and $t_2(x) = \int v_1(x) \frac{R(x)}{W(x)} dx$

* Special Methods for Determining a Particular Solution of the Nonhomogenous Equation $y'' + ay' + by = R$

** Case 1: RHS is a Polynomial of degree n

The right hand member R is a polynomial of degree n. If $b \neq 0$, we can alwasy find a polynomial of degree n that satisfies the equation.
We try a polynomial of the form $y_1(x) = \Sigma_{k = 0}^n a_k x^k$ with undetermined coefficients. Substituting in the differential equation $L(y) = R$
and equating coefficients of like powers of x, we may determine $a_n, a_{n - 1}, ..., a_1, a_0$ in succession.

If the coefficient b is 0, the equation $y'' + ay' = R$ cannot be satisfied by a polynomial of degree n, but it can be satisfied by a polynomial of degree n + 1 if $a \neq 0$. If both a and b are 0, the equation becomes $y'' = R$; its general solution is a polynomial of degree n + 2 obtained by 2 successive integrations.

** Case 2: RHS has the form $R(x) = p(x)e^{mx}$ where p is a polynomial of degree n and m is constant

In this case the change of variable $y = ue^{mx}$ transforms the differential equation $y'' + ay' + by = R$ into a new equation:

$u'' + (2m + a)u' + (m^2 + am + b)u = p$

This is the type discussed in case 1, so it always has a polynomial solution $u_1$. Hence the original equation has a particular solution of the form $y_1 = u_1(x)e^{mx}$, where $u_1$ is a polynomial.

If
- $m^2 + am + b \neq 0$, the degree of $u_1$ is the same as the degree of p
- $m^2 + am + b = 0$ but $2m + a \neq 0$, the degree of $u_1$ is one greater than that of p
- $m^2 + am + b = 0$ and $2m + a = 0$, the degree of $u_1$ is two greater than that of p

The method of undetermined coefficients can also be used if $ has the form $R(x) = p(x)e^{mx}\cos{\alpha x}$ or $R(x) = p(x)e^{mx} \sin{\alpha x}$ where p is a polynomial and m and $\alpha$ are constants.

In either case, there is always a particular solution of the form $y_1(x) = e^{mx}[q(x) \cos \alpha x + r(x) \sin \alpha x]$ where q and r are polynomials

** 8.17 Exercises

On exercise 7
