#+TITLE: Introduction to Differential Equations

* Introduction

We are trying to determine an unknown function from prescribed information expressed in the form of an equation involving at least one of the derivatives of the unknown function.

Differential equations are classified under two main headings: ordinary (one variable) and partial (two or more variables).

Here is an example of an ODE:

$f'(x) = f(x)$

and a PDE:

$\frac{\partial^2 f(x, y)}{\partial x^2} + \frac{\partial^2 f(x, y)}{\partial y^2} = 0$

* Terminology and Notation

We shall begin our study with first order equations which can be solved for $y'$ and written as follows:

$y' = f(x, y)$

A differentiable function $y = Y(x)$ will be called a solution of above on an interval $I$ if the function $Y$ and its derivative $Y'$ satisfy the relation

$Y'(x) = f[x, Y(x)]$

for every $x \in I$.

The simplest case occurs when $f(x, y)$ is independent of $y$. In this case, our initial equation becomes

$y' = Q(x)$

where $Q$ is assumed to be a given function defined on some interval $I$. To solve the differential equation above means to find a primitive of $Q$. 
If $Q$ is continuous and on the open interval $I$, then we can use the second fundamental theorem of calculus:

$y = \int Q(x) dx + C$

* A First-Order Differential Equation for the Exponential Function

** Theorem 8.1 | Existence-Uniqueness Theorem for $f'(x) = f(x)$

If $C$ is a given real number, then there is one and only one function $f$ which satisfies the differential equation

$f'(x) = f(x)$

for all real $x$ and which also satisfies the initial condition $f(x) = C$. This function is given by the formula

$f(x) = Ce^x$

* First-Order Linear Differential Equations

A differential equation of the form

$y' + P(x)y = Q(x)$

where $P, Q$ are given functions, is called a first-order linear differential equation. The terms involving the unknown function y and its derivative y' appear as a linear combination of y and y'.
The functions $P,Q$ are assumed to be continuous on some open interval $I$, and we seek all solutions $y$ defined on $I$.

First we consider the special case in which the right member, $Q(x)$ is identically 0. The equation

$y' + P(x)y = 0$

is called the *homogenous* or *reduced* equation corresponding to the above. 

If y is nonzero on $I$, our homogenous equation is equivalent to

$\frac{y'}{y} = -P(x)$

** Theorem 8.2 | Existence-Uniqueness for $y' + P(x)y = 0$

Assume $P$ is continuous on an open interval $I$. Choose any point $a$ in $I$ and let $b$ be any real number. Then there is one and only one function $y = f(x)$ which satisfies the initial-value problem

$y' + P(x)y = 0$ with $f(a) = b$

on the interval $I$. This function is given by the formula

$f(x) = be^{-A(x)}$ where $A(x) = \int_a^x P(t) dt$

** Theorem 8.3 | Existence-Uniqueness for $y' + P(x)y = Q(x)$

Assume $P$ and $Q$ are continuous in the open interval $I$. Choose any point $a$ in $I$ and let $b$ be any real number. Then there is one and only one function $y = f(x)$ which satisfies the initial-value problem

$y' + P(x)y = Q(x)$ with $f(a) = b$

on the interval $I$. This function is given by the formula

$f(x) = be^{-A(x)} + e^{-A(x)} \int_a^x Q(t)e^{A(t)} dt$

where $A(x) = \int_a^x P(t) dt$

* Exercises

On exercise 1

