#+TITLE: Chapter 4: Differential Calculus

* The Derivative of a Function

** Definition of a Derivative

The derivative $f'(x)$ is defined by the equation $f'(x) = \lim\limits_{h \to 0} \frac{f(x + h) - f(x)}{h}$ provided the limit exists. The number $f'(x)$ is also called the rate of change of $f$ at $x$

* The Algebra of Derivatives

** Theorem 4.1

Let $f$ and $g$ be two functions defined on a common interval. At each point where $f$ and $g$ have a derivative, the same is true of the sum $f + g$, the difference $f - g$, the product $f \cdot g$, and the quotient $f/g$ provided $g \neq 0$.

The derivatives of these functions are given by the following formulas:

- $(f + g)' = f' + g'$
- $(f - g)' = f' - g'$
- $(f \cdot g)' = f \cdot g' + g \cdot f'$
- $(\frac{f}{g})' = \frac{g \cdot f' - f \cdot g'}{g^2}$ where $g(x) \neq 0$

Derivatives are linear: $(c_1 f + c_2 g)' = c_1 f' + c_2 g'$, which in turn can be extended to arbitrary finite sums:  $(\sum_{i = 1}^n c_i \cdot f_i)' = \sum_{i = 1}^n c_i \cdot f_i'$

* The Chain Rule for Differentiating Composite Functions

** Theorem 4.1 : Chain Rule

Let $f$ be the composition of two functions, $u$ and $v$, say $f = u \circ v$. Suppose that both derivatives $v'(x)$ and $u'(y)$ exist, where $y = v(x)$. Then the derivative  $f'(x)$ also exists and is given by the formula $f'(x) = u'(y) \cdot v'(x)$

Expressed as an equation involving functions rather than numbers, the chain rule assumes the following form: $(u \circ v)' = (u' \circ v) \cdot v'$, or $u(v)' = u'(v) \cdot v'$.  

* Applications of the Chain Rule. Related Rates and Implicit Differentiation

  I thought these exercises would never end. Related rates are tough when they rely on implicit assumptions (physics, shapes, etc)

* Applications of Differentiation to Extreme Values of Functions

** Definition of Relative Maximum

A function $f$, defined on a set $S$, is said to have a relative maximum at a point $c \in S$ if there is some open interval $I$ containing $c$ such that $f(x) \leq f(c)$ for all $x$ which lie in $I \cap  S$. 

The concept of relative minimum is similarly defined by reversing the inequality. 

** Definition of Extremum 

A number which is either a relative maximum or a relative minimum of a function $f$ is called an extreme value, or an extremum of $f$. 

** Theorem 4.3 : Vanishing of the Derivative at an Interior Extremum

Let $f$ be defined on an open interval $I$, and assume that $f$ has a relative maximum or a relative minumum at an interior point $c$ of $I$. If the derivative $f'(c)$ exists, then $f'(c) = 0$.

* The Mean-Value Theorem for Derivatives

The mean-value theorem for derivatives holds a position of importance in calculus because many properties of functions can easily be deduced from it. 

** Theorem 4.4 : Rolle's Theorem 

Let $f$ be a function which is continuous everywhere on a closed interval $[a, b]$ and has a derivative at each point of the open interval $(a, b)$. Also, assume that $f(a) = f(b)$. Then there is at least one point $c$ in the open interval $(a, b)$ such that $f'(c) = 0$.

** Theorem 4.5 : Mean-Value Theorem for Derivatives 

Assume that $f$ is continuous everywhere on a closed interval $[a, b]$ and has a derivative at each point of the open interval $(a, b)$. Then there is at least one interior point $c$ of $(a, b)$ for which $f(b) - f(a) = f'(c)(b - a)$

** Theorem 4.6 : Cauchy's Mean-Value Formula

Let $f$ and $g$ be two functions continuous on a closed interval $[a, b]$  and having derivatives in the open interval $(a, b)$. Then, for some $c$ in $(a, b)$, we have $f'(c)[g(b) - g(a)] = g'(c)[f(b) - f(a)]$

* Exercises

** Theorem : Intermediate Value Theorem for Derivatives

Assume $f$ has a derivative everywhere on the open interval $I$. Choose $a < b \in I$. Then $f'$ takes on every value between $f'(a)$ and $f'(b)$ somewhere in $(a, b)$

* Applications of the Mean-Value Theorem to Geometric Properties of Functions

The mean-value theorem may be used to deduce properties of a function from a knowledge of the algebraic sign of its derivative

** Theorem 4.7

Let $f$ be a function which is continuous on a closed interval $[a, b]$ and assume $f$ has a derivative at each point of the open interval $(a, b)$. Then we have
a. If $f'(x) > 0$ for every $x \in (a, b)$, then $f$ is strictly increasing on $[a, b]$
b. If $f'(x) < 0$ for every $x \in (a, b)$, then $f$ is strictly decreasing on $[a, b]$
a. If $f'(x) = 0$ for every $x \in (a, b)$, then $f$ is constant throughout $[a, b]$

** Theorem 4.8

Assume $f$ is continuous on a closed interval $[a, b]$ and assume that the derivative $f'$ exists everywhere in the open interval $(a, b)$, except possibly at a point $c$. 
a. If $f'(x)$ is positive for all $x < c$ and negative for all $x > c$, then $f$ has a relative maximum at $c$
b. If $f'(x)$ is negative for all $x < c$ and positive for all $x > c$, then $f$ has a relative minimum at $c$

* Second-Derivative Test for Extrema 

If a function is continuous on a closed interval $[a, b]$, the extreme-value theorem tells us that it has an absolute maximum and and absolute minimum somewhere in $[a, b]$. If $f$ has a derivative at each interior point, then the only places where extrema can occur are: 
1. At the endpoints $a, b$
2. At those interior points $x$ where $f'(x) = 0$

Points of type 2 are called *critical points* of $f$. 
Usually the behavior of $f$ at a critical point can be determined from the algebraic sign of the derivative near $c$.

** Theorem 4.9 : Second Derivative Test for an Extremum at a Critical Point

Let $c$ be a critical point of $f$ in an open interval $(a, b)$; that is, assume $a < c < b$ and $f'(c) = 0$. Assume also that the second derivative $f''$ exists in $(a, b)$. Then we have the following: 
a. If $f''$ is negative in $(a, b)$, then $f$ has a relative maximum at $c$
b. If $f''$ is positive in $(a, b)$, then $f$ has a relative minimum at $c$

If $f''$ is continuous at $c$, and if $f''(c) \neq 0$, there will be a neighborhood of $c$ in which $f''$ has the same sign as $f''(c)$. Therefore, if $f'(c) = 0$, the function $f$ has a relative maximum at $c$ if $f''(c)$ is negative, or a relative minimum if $f''(c)$ is positive.

** Theorem 4.10 : Derivative Test for Convexity

Assume $f$ is continuous on $[a, b]$ and has a derivative in the open interval $(a, b)$. If $f'$ is increasing on $(a, b)$, then $f$ is convex on $[a, b]$. In particular, $f$ is convex if $f''$ exists and is non-negative in $(a, b)$.

* Curve Sketching

#+BEGIN_SRC R
library(tidyverse)
library(patchwork)
library(paletteer)
library(rlang)

f <- expr(x^2 - 3*x + 2)
f_p <- D(f, "x")
f_dp <- D(f_p, "x")

h <- expr((1 / 6) * x^2 + (1 / 12) * cos(2 * x))

get_derivatives <- function(funk, iter = 0) {
    if (funk == 0) return(0)
    ## max out iterations for periodic functions
    if (iter == 5) return(0)
    else list(funk,
              get_derivatives(D(funk, "x"),
                              iter = iter + 1)) %>% flatten
}

eval_exp <- function(expr, x) expr %>% deparse %>% parse_expr %>% eval

get_derivatives(f)
get_derivatives(h)
#+END_SRC

1. find all points x such that f'(x) = 0

#+BEGIN_SRC R
get_roots <- function(exp) {
    if (is.numeric(exp)) return(exp)
    f_exp <- function(x) eval(exp)
    seq(-100, 100, by = .1) %>%
        enframe(value = "x", name = NULL) %>%
        mutate(y = f_exp(x),
               root = ifelse(between(y, -.00001, .00001), TRUE, FALSE)) %>%
        filter(root)
}

f %>% get_roots()
f %>% get_derivatives() %>% map(get_roots)

#+END_SRC

2, 3. determine those intervals in which f, f' is monotonic

#+BEGIN_SRC R
get_monotonic_intervals <- function(funk) {
    seq(-100, 100, by = .1) %>%
        enframe(value = "x", name = NULL) %>%
        mutate(y = eval_exp(funk, x),
               sgn = ifelse(lead(y) > y, "up", "down"),
               change = ifelse(sgn != lag(sgn), "change", "same") %>% ifelse(is.na(.), "same", .),
               interval = case_when(is.na(lag(change)) ~ "begin",
                                    lag(change) == "change" ~ "begin",
                                    is.na(lead(change)) ~ "end",
                                    lead(change) == "change" ~ "end",
                                    change == "change" ~ "inflection",
                                    TRUE ~ "interior")) %>%
        filter(interval %in% c("begin", "end") | change == "change")
}

get_monotonic_intervals(f)
#+END_SRC

4. make a sketch of the graph of f

#+BEGIN_SRC R
## plots one function
simple_plot <- function(expr, expr_name) {
    seq(-100, 100, by = .5) %>%
        map(~ eval_exp(expr, .x)) %>%
        enframe(name = "x", value = "y") %>%
        unnest() %>%
        ggplot(aes(x = x, y = y)) +
        geom_line(color = "orange") +
        ggtitle(expr_name)
}

## plots all the derivatives overlaying
simple_plot_overlap <- function(ls) {
    ls %>% map(~ seq(-100, 100, by = .5) %>%
                 map(function(.y) eval_exp(.x, .y)) %>%
                 enframe(name = "x", value = "y") %>%
                 unnest()) %>%
        set_names(ls) %>% 
        imap(~ add_column(.data = .x, "grp" = .y)) %>%
        bind_rows() %>%
        ggplot(aes(x = x, y = y, group = grp, color = grp)) +
        geom_line() +
        scale_color_paletteer_d("nord::victory_bonds") +
        ggtitle("f and its derivatives")
}

all_together <- function(deriv_list) {
    deriv_list %>%
        list(simple_plot_overlap(.),
             imap(., ~ simple_plot(.x, .y))) %>%
        flatten() %>%
        .[(length(deriv_list) + 1):length(.)] %>%
        reduce(`+`)
}

f %>% get_derivatives() %>% all_together()
#+END_SRC

5. Do it for all the expressions

#+BEGIN_SRC R
list("p1" = expr(x^2 - 3 * x + 2),
     "p2" = expr(x^3 - 4 * x),
     "p3" = expr((x - 1)^2 * (x + 2)),
     "p4" = expr(x^3 - 6 * x^2 + 9*x + 5),
     "p5" = expr(2 + (x - 1)^4),
     "p6" = expr(1 / x^2),
     "p7" = expr(x + (1 / x^2)),
     "p8" = expr(1 / ((x - 1) * (x - 3))),
     "p9" = expr(x / (1 + x^2)),
     "p10" = expr((x^2 - 4) / (x^2 - 9)),
     "p11" = expr(sin(x)^2),
     "p12" = expr(x - sin(x)),
     "p13" = expr(x + cos(x)),
     "p14" = expr((1/6) * x^2 + (1/12) * cos(2 * x))) -> pset

pset %>%
    map(get_roots)

pset %>%
    map(get_derivatives)
#+END_SRC

1. Find all points for which f'(x) = 0

#+BEGIN_SRC R
pset %>%
    map(~ get_derivatives(.x) %>% map(get_roots))
#+END_SRC

2. Determine those intervals for which f, f' are monotonic

#+BEGIN_SRC R
## f
pset %>%
    map(get_monotonic_intervals)

## f'
pset %>%
    map(get_derivatives) %>%
    flatten() %>%
    map(safely(get_monotonic_intervals))
#+END_SRC

4. Plot them!

#+BEGIN_SRC R
pset$p1 %>% get_derivatives() %>% all_together()
pset$p2 %>% get_derivatives() %>% all_together()
pset$p3 %>% get_derivatives() %>% all_together()
pset$p4 %>% get_derivatives() %>% all_together()
pset$p5 %>% get_derivatives() %>% all_together()
pset$p6 %>% get_derivatives() %>% all_together()
pset$p7 %>% get_derivatives() %>% all_together()
pset$p8 %>% get_derivatives() %>% all_together()
pset$p9 %>% get_derivatives() %>% all_together()
pset$p10 %>% get_derivatives() %>% all_together()
pset$p11 %>% get_derivatives() %>% all_together()
pset$p12 %>% get_derivatives() %>% all_together()
pset$p13 %>% get_derivatives() %>% all_together()
pset$p14 %>% get_derivatives() %>% all_together()
#+END_SRC

* Worked Examples of Extremum Problems

There are 2 simple principles which can be used to solve many extremum problems: 

** Example 1: Constant Sum, Maximum Product Principle

Given a positive number $S$, Prove that among the choices of positive numbers $x$ and $y$ with $x + y = S$, the product $xy$ is largest when $x = y = \frac{1}{2}S$

** Example 2: Constant Product, Minimum Sum Principle

Given a positive number $P$, Prove that among all choices of positive numbers $x, y$ with $xy = P$, the sum $x + y$ is smallest when $x = y = \sqrt P$

* Exercises

on exercise 17

