* Some Applications of Integration
:PROPERTIES:
:header-args: :session R-session :results output value table :colnames yes
:END:

#+NAME: round-tbl
#+BEGIN_SRC emacs-lisp :var tbl="" fmt="%.1f"
(mapcar (lambda (row)
          (mapcar (lambda (cell)
                    (if (numberp cell)
                        (format fmt cell)
                      cell))
                  row))
        tbl)
#+end_src

** Introduction 

In this chapter, we will show that the areas of more general regions can also be expressed as integrals. We will also discuss concepts like volume, work, averages. Then we will finish up with a study of properties of functions defined by integrals. 

** The Area of a Region Between Two Graphs Expressed as an Integral 

*** Theorem 2.1

Assume $f$ and $g$ are integrable and satisfy $f \leq g$ on $[a, b]$. Then the region $S$ between their graphs is measurable and its area $a(S)$ is given by the integral $a(S) = \int_a^b [g(x) - f(x)] dx$ 

** Worked Examples

In these, I am just going to write down the things I think will be useful. 

*Example 2:*

In examples where the interval $[a, b]$ can be broken up into a finite number of subintervals such that either $f \leq g$ or $g \leq f$ in each subinterval, our formula above becomes $a(S) = \int_a^b |g(x) - f(x)| dx$ 

*Example 3:*

The area of a disk of radius $r$ is $r^2$ times the area of a unit disk

*** Definition $\pi$

We define the number $\pi$ to be the area of a unit disk

Thus, $A(r) = \pi r^2$

*Example 4:*

Let $f$ be non-negative and integrable on $[a, b]$, and let $S$ be its ordinate set. If we apply a similarity transformation with a positive factor $k$, then $kS$ is the ordinate set of a new function, say $g$, over the interval $[ka, kb]$. A point $(x, y)$ is on the graph of $g$ iff the point $(x/k, y/k)$ is on the graph of $f$. Hence $y/k = f(x/k)$, and so $y = k f(x/k)$. In other words, the new function $g$ is related to $f$ by the formula $g(x) = k f(\frac{x}{k})$ for each $x$ in $[ka, kb]$. Therefore, the area of $kS$ is given by

$a(kS) = \int_{ka}^{kb} g(x) dx = k \int_{ka}^{kb} f(\frac{x}{k}) dx = k^2 \int_a^b f(x) dx = k^2a(S)$

 *Example 5:*

Ordinarily we use the integral to calculate areas, but sometimes we can use our knowledge of area to calculate integrals. 

*** Theorem 2.2

For $a > 0, b > 0$ and $n$ a positive integer, we have $\int_a^b x^{1/n} dx = \frac{b^{1 + \frac{1}{n}} - a^{1 + \frac{1}{n}}}{1 + \frac{1}{n}}$

** The Trigonometric Functions 

*** Definition: Fundamental Properties of the Sine and Cosine 

1. Domain of Definition: The sine and cosine functions are defined everywhere on the real line
2. Special Values: We have $cos(0) = sin \frac{1}{2}\pi = 1$, $cos(\pi) = -1$
3. Cosine of a Difference: For all $x$ and $y$, we have $cos(y - x) = cos(y) cos(x) + sin(y) sin(x)$
4. Fundamental Inequalities: For $0 < x < \frac{1}{2}\pi$, we have $0 < cos(x) < \frac{sin(x)}{x} < \frac{1}{cos(x)}$

*** Theorem 2.3

If two functions $sin$ and $cos$ satisfy properties 1 through 4, then they also satisfy the following properties: 

a. Pythagorean Identity: $sin^2x + cos^2x = 1$ for all $x$ 
b. Special Values: $sin 0 = cos \frac{\pi}{2} = sin \pi = 0$ 
c. Even and Odd Properties: The cosine is an even function and the sine is an odd function. That is, for all x we have $cos(-x) = cos(x)$, $sin(-x) = - sin(x)$
d. Co-relations: For all x, we have $sin(\frac{\pi}{2} + x) = cos(x)$, $cos(\frac{\pi}{2} + x) = -sin(x)$ 
e. Periodicity: For all x, we have $sin(x + 2\pi) = sin(x)$, $cos(x + 2\pi) = cos(x)$ 
f. Addition Formulas: For all $x$ and $y$, we have $cos(x + y) = cos(x)cos(y) - sin(x)sin(y)$ and $sin(x + y) = cos(x)sin(y) + sin(x)cos(y)$ 
g. Difference Formulas: For all $a$ and $b$, we have $sin(a) - sin(b) = 2 sin \frac{a - b}{2} cos \frac{a + b}{2}$ and $cos(a) - cos(b) = -2 sin\frac{a - b}{2} sin \frac{a + b}{2}$
h. Monotonicity: In the interval $[0, \frac{\pi}{2}]$, the sine is strictly increasing an the cosine is strictly decreasing

Further properties of the sine and cosine function are discussed in the next set of exercises. Two formulas that are particularly useful in calculus are the double-angle or duplication formulas: 

- $sin(2x) = 2 sin(x) cos(x)$
- $cos(2x) = cos^2(x) - sin^2(x) = 1 - 2 sin^2(x)$

** Integration Formulas for the Sine and Cosine

The monotonicity properties (h), co-relations (d), and periodicity (e) properties show that the sine and cosine functions are piecewise monotonic on every interval. Therefore, by repeated use of theorem 1.12 (If $f$ is monotonic on a closed interval $[a, b]$, then $f$ is integrable on $[a, b]$), we see that the sine and cosine are integrable on every finite interval. Next we shall calculute their integrals by applying theorem 1.14 (Assume $f$ is decreasing on $[a, b]$. Let $x_k = a + k \frac{b - a}{n}$ for $k = 0, 1, ..., n$. If $I$ is any number which satisfies the inequalities 
$\frac{b - a}{n} \sum_{k = 0}^{n} f(x_k) \leq I \leq \frac{b - a}{n} \sum_{k = 1}^{n - 1} f(x_k)$ for every integer $n \geq 1$, then $I = \int_a^b f(x) dx$.)

This makes use of the following inequalities:

*** Theorem 2.4

If $0 < a < \frac{\pi}{2}$ and $n \geq 1$, we have $\frac{a}{n} \sum_{k = 1}^{n} cos(\frac{ka}{n}) < sin(a) < \frac{a}{n} \sum_{k = 0}^{n - 1} cos(\frac{ka}{n})$


*** Theorem 2.5 

If two functions $sin$ and $cos$ satisfy the fundamental properties 1 through 4, then for every real $a$ we have 

$\int_0^a cos(x) dx = sin(a)$, $\int_0^a sin(x) dx = 1 - cos(a)$


General Formulas: 

- $\int_a^b cos(x) dx = sin(b) - sin(a)$
- $\int_a^b sin(x) dx = -(cos(b) - cos(a))$
- $\int_a^b cos(cx) dx = \frac{1}{c} \int_{ac}^{bc} cos(x) dx = \frac{1}{c} [sin(bc) - sin(ac)]$
- $\int_a^b sin(cx) dx = \frac{1}{c} \int_{ac}^{bc} sin(x) dx = \frac{1}{c} [cos(ac) - cos(bc)]$

Orthogonality Relations: 
- $\int_0^{2 \pi} sin(nx)cos(mx) dx = \int_0^{2 \pi} sin(nx)sin(mx) dx = \int_0^{2 \pi} cos(nx)cos(mx) dx = 0$
- $\int_0^{2 \pi} sin^2(nx) dx = \int_0^{2 \pi} cos^2 (nx) dx = \pi$ if $n \neq 0$


** A Geometric Description of the Sine and Cosine Functions

+ The measure of an angle $AOP$ is $x$ radians if $\frac{x}{2}$ is the area of the sector $AOP$ cut from a unit circular disk. 

** Polar Coordinates

We can also locate points in the plane with polar coordinates. The two numbers $r$ and $\theta$ are called the polar coordinates of $P$.

They are related to the rectangular coordinates $x = rcos(\theta)$, $y = rsin(\theta)$

The radial distance $r$ is uniquely determined, $r = \sqrt{x^2 + y^2}$, but the polar angle $\theta$ is determined only up to integer multiples of $2 \pi$.

** The Integral for Area in Polar Coordinates

Let $f$ be a non-negative function defined on an interval $[a, b]$, where $0 \leq b - a \leq 2\pi$. The set of all points with polar coordinates $(r, \theta)$ satisfy the inequalities $0 \leq r \leq f(\theta)$, $a \leq \theta \leq b$ is called the *radial set* of $f$ over $[a, b]$. 

If $f$ is constant on $[a, b]$, its radial set is a circular sector subtending an angle of $b - a$ radians. Over each of the $n$ open subintervals $(\theta_{k - 1}, \theta_k)$ of $[a, b]$ in which $s$ is constant, say $s(\theta) = s_k$, the graph of $s$ in polar coordinates is the circular arc of radius $s_k$, and its radial set is a circular sector subtending an angle of $\theta_k - \theta_{k - 1}$ radians. Because of the way we have defined angular measure, the area of this sector is $\frac{1}{2}(\theta_{k} - \theta_{k - 1})s_k^2$. Since $b - a \leq 2\pi$, none of these sectors overlap, so by additivity, the area of the radial set of $s$ over the full interval $[a, b]$ is given by

$a(S) =  \frac{1}{2} \sum_{k = 1}^n s_k^2 (\theta_k - \theta_{k - 1}) = \frac{1}{2} \int_a^b s^2(\theta) d\theta$

Thus for step functions, the area of a radial set has been expressed as an integral. Now we show that this integral formula holds more generally:

*** Theorem 2.6

Let $R$ denote the radial set of a non-negative function $f$ over an interval $[a, b]$, where $0 \leq b - a \leq 2 \pi$, and assume that $R$ is measurable. If $f^2$ is integrable on $[a, b]$ the area of $R$ is given by the integral

$a(R) = \frac{1}{2} \int_a^b f^2(\theta) d\theta$

** Application of Integration to the Calculation of Volume

We assume there exist certain sets $S$ of points in three-dimensional space, which we call measurable sets, and a set function $v$, called the volume of $S$. We use the symbol $\mathcal{A}$ to denote the class of all measurable sets in 3-dimensional space, and we call each set $S$ in $\mathcal{A}$ a solid. 

*** Axiomatic Definition of Volume

We assume there exists a class $\mathcal{A}$ of solids and a set function $v$, whose domain is $\mathcal{A}$, with the following properties: 

1. Non-negative Property: For each set $S$ in $\mathcal{A}$, we have $v(S) \geq 0$ 
2. Additive Property: If $S$ and $T$ are in $\mathcal{A}$, then $S \cup T$ and $S \cap T$ are in $\mathcal{A}$, and we have $v(S \cup T) = v(S) + v(T) - v(S \cap T)$
3. Difference Property: If $S$ and $T$ are in $\mathcal{A}$ with $S \subseteq T$, then $T - S$ is in $\mathcal{A}$, and we have $v(T - S) = v(T) - v(S)$.
   - This also implies the monotone property: $v(S) \leq v(T)$ for sets $S, T \in \mathcal{A}$ with $S \subseteq T$ 
   - The monotone property shows that every bounded plane set $S \in \mathcal{A}$ has zero volume, where a plane set is bounded if it is a subset of some square in the plane 
4. Cavalieri's Principle: If $S$ and $T$ are two Cavalieri solids in $\mathcal{A}$ with $a(S \cap F) \leq a(T \cap F)$ for every plane $F$ perpendicular to a given line, then $v(S) \leq v(T)$
5. Choice of Scale: Every box $B$ is in $\mathcal{A}$. If the edges of $B$ have lengths $a, b, c$, then $v(B) = abc$.
6. Every convex set is in $\mathcal{A}$

*** Theorem 2.7

Let $R$ be a Cavalieri solid in $\mathcal{A}$ with a cross-sectional area function $a_R$ which is integrable on an interval $[a, b]$ and zero outside $[a, b]$. Then the volume of $R$ is equal to the integral of the cross-sectional area:

$v(R) = \int_a^b a_R (u) du$

*** Example: Volume of a Solid of Revolution 

Let $f$ be a function which is non-negative and integrable on the interval $[a, b]$. If the ordinate set of this function is revolved about the x-axis, it sweeps out a solid of revolution. Each cross section cut by a plane perpendicular to the x-axis is a circular disk. The area of the circular disk cut at the point $x$ is $\pi f^2 (x)$. Therefore, by theorem 2.7, the volume of the solid (if the solid is in $\mathcal{A}$) is equal to the integral $\int_a^b \pi f^2(x) dx$, if the integral exists.

More generally, suppose we have two non-negative functions $f$ and $g$ which are integrable on an interval $[a, b]$ and satisfy $f \leq g$ on $[a, b]$. When the region between their graphs is rotated about the x-axis, it sweeps out a solid of revoltion such that each cross section cut by a plane perpendicular to the x-axis at the point x is an annulus (a region bounded by two concentric circles) with area $\pi g^2(x) - \pi f^2(x)$. Therefore if $g^2 - f^2$ is integrable, the volume of such a solid (if the solid is in $\mathcal{A}$) is given by the integral $\int_a^b \pi[g^2(x) - f^2(x)] dx$

** Application of Integration to the Concept of Work

Work is a measure of the energy expended by a force in moving a particle from one point to another. 

*** Fundamental Properties of Work

Let $W_\alpha (f)$ denote the work done by a force function $f$ in moving a particle from $a$ to $b$. Then work has the following properties: 

1. Additive Property: If $a < c < b$, then $W_a^b (f) = W_a^c (f) + W_c^b (f)$
   We can extend it by induction s.t. if $a = x_0 < x_1 < ... < x_n = b$, then $W_a^b = \sum_{k = 1}^b W_k$
2. Monotone Property: If $f \leq g$ on $[a, b]$, then $W_a^b(f) \leq W_a^b(g)$. That is, a greater force does greater work.
3. Elementary Formula: If $f$ is constant, say $f(x) = x$ for all $x$ in the open interval $(a, b)$, then $W_a^b(f) = c \cdot (b - a)$

*** Theorem 2.8

Suppose work has been defined for a class of force functions $f$ in such a way that it satisfies properties $1, 2, 3$. Then the work done by an integrable force function $f$ in moving a particle from $a$ to $b$ is equal to the integral of $f$, $W_a^b(f) = \int_a^b f(x) dx$

** Average Value of a Function

*** Definition: Arithmetic Mean

If $a_1, ..., a_n$ are $n$ real numbers, their arithmetic mean $\bar{a}$ is defined by $\frac{1}{n}\sum_{k = 1}^n a_k$ and if the numbers $a_k$ are the values of a function $f$ at $n$ distinct points, say $a_k = f(x_k)$, then the number $\frac{1}{n}\sum_{k = 1}^n f(x_k)$ is the arithmetic mean of the function values $f(x_1), ..., f(x_n)$. 

 
*** Definition of Average Value of a Function on an Interval

If $f$ is integrable on an interval $[a, b]$, we define $A(f)$, the average value of $f$ on $[a, b]$, by the formula: 

$A(f) = \frac{1}{b - a}\int_a^b f(x) dx$ 

*** Definition for Weighted Means

If $w_1, ..., w_n$ are $n$ non-negative numbers (called weights), not all zero, the weighted arithmetic mean $\bar{a}$ of $a_1, .., a_n$ is defined by the formula $\frac{\sum_{k = 1}^n w_k a_k}{\sum_{k = 1}^n w_k}$

When the weights are equal, this reduces to the ordinary arithmetic mean. The extension of this concept to integral functions is given by the formula $A(f) = \frac{\int_a^b w(x)f(x) dx}{\int_a^b w(x) dx}$

*** Definition: Center of Mass

$\bar{x} = \frac{\int_0^a x \rho(x) dx}{\int_0^a \rho (x) dx}$, where the numerator is the first moment

*** Definition: Radius of Gyration

$r^2 = \frac{\int_0^a x^2 \rho(x) dx}{\int_0^a \rho(x) dx}$, where the numerator is the second moment or the moment of inertia 

Weighted averagese like these two above also play a role in probability, where the concepts of expectation and variance play the same role as center of mass and moment of inertia. 






