* Some Applications of Integration
:PROPERTIES:
:header-args: :session R-session :results output value table :colnames yes
:END:

#+NAME: round-tbl
#+BEGIN_SRC emacs-lisp :var tbl="" fmt="%.1f"
(mapcar (lambda (row)
          (mapcar (lambda (cell)
                    (if (numberp cell)
                        (format fmt cell)
                      cell))
                  row))
        tbl)
#+end_src

** Introduction 

In this chapter, we will show that the areas of more general regions can also be expressed as integrals. We will also discuss concepts like volume, work, averages. Then we will finish up with a study of properties of functions defined by integrals. 

** The Area of a Region Between Two Graphs Expressed as an Integral 

*** Theorem 2.1

Assume $f$ and $g$ are integrable and satisfy $f \leq g$ on $[a, b]$. Then the region $S$ between their graphs is measurable and its area $a(S)$ is given by the integral $a(S) = \int_a^b [g(x) - f(x)] dx$ 

** Worked Examples

In these, I am just going to write down the things I think will be useful. 

*Example 2:*

In examples where the interval $[a, b]$ can be broken up into a finite number of subintervals such that either $f \leq g$ or $g \leq f$ in each subinterval, our formula above becomes $a(S) = \int_a^b |g(x) - f(x)| dx$ 

*Example 3:*

The area of a disk of radius $r$ is $r^2$ times the area of a unit disk

*** Definition $\pi$

We define the number $\pi$ to be the area of a unit disk

Thus, $A(r) = \pi r^2$

*Example 4:*

Let $f$ be non-negative and integrable on $[a, b]$, and let $S$ be its ordinate set. If we apply a similarity transformation with a positive factor $k$, then $kS$ is the ordinate set of a new function, say $g$, over the interval $[ka, kb]$. A point $(x, y)$ is on the graph of $g$ iff the point $(x/k, y/k)$ is on the graph of $f$. Hence $y/k = f(x/k)$, and so $y = k f(x/k)$. In other words, the new function $g$ is related to $f$ by the formula $g(x) = k f(\frac{x}{k})$ for each $x$ in $[ka, kb]$. Therefore, the area of $kS$ is given by

$a(kS) = \int_{ka}^{kb} g(x) dx = k \int_{ka}^{kb} f(\frac{x}{k}) dx = k^2 \int_a^b f(x) dx = k^2a(S)$

 *Example 5:*

Ordinarily we use the integral to calculate areas, but sometimes we can use our knowledge of area to calculate integrals. 

*** Theorem 2.2

For $a > 0, b > 0$ and $n$ a positive integer, we have $\int_a^b x^{1/n} dx = \frac{b^{1 + \frac{1}{n}} - a^{1 + \frac{1}{n}}}{1 + \frac{1}{n}}$

** The Trigonometric Functions 

*** Definition: Fundamental Properties of the Sine and Cosine 

1. Domain of Definition: The sine and cosine functions are defined everywhere on the real line
2. Special Values: We have $cos(0) = sin \frac{1}{2}\pi = 1$, $cos(\pi) = -1$
3. Cosine of a Difference: For all $x$ and $y$, we have $cos(y - x) = cos(y) cos(x) + sin(y) sin(x)$
4. Fundamental Inequalities: For $0 < x < \frac{1}{2}\pi$, we have $0 < cos(x) < \frac{sin(x)}{x} < \frac{1}{cos(x)}$

*** Theorem 2.3

If two functions $sin$ and $cos$ satisfy properties 1 through 4, then they also satisfy the following properties: 

a. Pythagorean Identity: $sin^2x + cos^2x = 1$ for all $x$ 
b. Special Values: $sin 0 = cos \frac{\pi}{2} = sin \pi = 0$ 
c. Even and Odd Properties: The cosine is an even function and the sine is an odd function. That is, for all x we have $cos(-x) = cos(x)$, $sin(-x) = - sin(x)$
d. Co-relations: For all x, we have $sin(\frac{\pi}{2} + x) = cos(x)$, $cos(\frac{\pi}{2} + x) = -sin(x)$ 
e. Periodicity: For all x, we have $sin(x + 2\pi) = sin(x)$, $cos(x + 2\pi) = cos(x)$ 
f. Addition Formulas: For all $x$ and $y$, we have $cos(x + y) = cos(x)cos(y) - sin(x)sin(y)$ and $sin(x + y) = cos(x)sin(y) + sin(x)cos(y)$ 
g. Difference Formulas: For all $a$ and $b$, we have $sin(a) - sin(b) = 2 sin \frac{a - b}{2} cos \frac{a + b}{2}$ and $cos(a) - cos(b) = -2 sin\frac{a - b}{2} sin \frac{a + b}{2}$
h. Monotonicity: In the interval $[0, \frac{\pi}{2}]$, the sine is strictly increasing an the cosine is strictly decreasing

Further properties of the sine and cosine function are discussed in the next set of exercises. Two formulas that are particularly useful in calculus are the double-angle or duplication formulas: 

- $sin(2x) = 2 sin(x) cos(x)$
- $cos(2x) = cos^2(x) - sin^2(x) = 1 - 2 sin^2(x)$

** Integration Formulas for the Sine and Cosine

The monotonicity properties (h), co-relations (d), and periodicity (e) properties show that the sine and cosine functions are piecewise monotonic on every interval. Therefore, by repeated use of theorem 1.12 (If $f$ is monotonic on a closed interval $[a, b]$, then $f$ is integrable on $[a, b]$), we see that the sine and cosine are integrable on every finite interval. Next we shall calculute their integrals by applying theorem 1.14 (Assume $f$ is decreasing on $[a, b]$. Let $x_k = a + k \frac{b - a}{n}$ for $k = 0, 1, ..., n$. If $I$ is any number which satisfies the inequalities 
$\frac{b - a}{n} \sum_{k = 0}^{n} f(x_k) \leq I \leq \frac{b - a}{n} \sum_{k = 1}^{n - 1} f(x_k)$ for every integer $n \geq 1$, then $I = \int_a^b f(x) dx$.)

This makes use of the following inequalities:

*** Theorem 2.4

If $0 < a < \frac{\pi}{2}$ and $n \geq 1$, we have $\frac{a}{n} \sum_{k = 1}^{n} cos(\frac{ka}{n}) < sin(a) < \frac{a}{n} \sum_{k = 0}^{n - 1} cos(\frac{ka}{n})$

still trying to figure out this proof 
