* Calculus Vol 1

* Introduction 

** Part 1. Historical Introduction 

Integral calculus deals with the problem of area. Differential calculus deals with the problem of tangents. 

This section is mainly interested in showing the archimedean construction of the integral applied to a parabola. The exercises have you derive more general integrals of functions

** Part 2. Some Basic Concepts of the Theory of Sets

*** Definition | Set Equality 

Two sets $A$ and $B$ are said to be equal (or identical) if they consist of exactly the same elements, in which case we write $A = B$. If one of the sets contains an element not in the other, we say the sets are unequal and write $A \neq B$.


*** Definition | Subset

A set $A$ is said to be a subset of a set $B$, and we write $A \subset B$ whenever every element of $A$ also belongs to $B$. We say that $A$ is contained in $B$, or that $B$ contains $A$. The relation $\psubset$ is referred to as set inclusion.

To help simplify the language, we call a collection of sets a class. Capital script letters like $\mathcal{A}, \mathcal{B}, \mathcal{C}, ...$ are used to denote classes. 

** Part 3. A Set of Axioms for the Real-Number System 

The axioms we list here fall in a natural way into three groups which we can refer to as field axioms, order axioms, and the least upper bound axiom. 

**The Field Axioms**

*** Axiom 1: Commutative Laws: x + y = y + x 
*** Axiom 2: Associative Laws: x + (y + z) = (x + y) + z
*** Axiom 3: Distributive Law: x(y + z) = xy + xz
*** Axiom 4: Existence of Identity Elements: There exist two distinct real numbers, which we denote by 0 and 1, such that for every real x we have x + 0 = x and 1 * x = x 
*** Axiom 5: Existence of Negatives: For every real number x there is a real number y such that x + y = 0 
*** Axiom 6: Existence of Reciprocals: For every real number $x /neq 0$ there is a real number y such that $xy = 1$ 

From the above axioms, we can deduce all the usual laws of elementary algebra. The most important of these laws are collected below as a list of theorems.

*** Theorem 1.1: Cancellation Law for Addition: If a + b = a + c, then b = c
*** Theorem 1.2: Possibility of Subtraction: Given a and b, there is exactly one x such that a + x = b. This x is denoted by b - a. In particular, 0 - a is written simply -a and is called the negative of a. 
*** Theorem 1.3: b - a = b + (-a)
*** Theorem 1.4: -(-a) = a 
*** Theorem 1.5: a(b - c) = ab - ac 
*** Theorem 1.6: 0*a = a*0 = 0 
*** Theorem 1.7: Cancellation Law for Multiplication: If ab = ac and $a /neq 0$, then b = c. In particular, this shows that the number 1 of axiom 4 is unique. 
*** Theorem 1.8: Possibility of Division: Given a and b with $a \neq 0$, there is exactly one x such that $ax = b$. This x is denoted by b/a, and is called the quotient of b and a. In particular, 1/a is also written $a^{-1}$ and is called the reciprocal of a
*** Theorem 1.9: If $a \neq 0$, then b/a = b * $a^{-1}$
*** Theorem 1.10: If $a \neq 0$, then $(a^{-1})^{-1} = a$ 
*** Theorem 1.11: If ab = 0, then a = 0 or b = 0
*** Theorem 1.12: (-a)b = -(ab) and (-a)(-b) = ab 
*** Theorem 1.13: (a/b) + (c/d) = (ad + bc)/(bd) if $b, d /neq 0$
*** Theorem 1.14: (a/b)(c/d) = ac/bd if $b, d \neq 0$ 
*** Theorem 1.15: (a/b)/(c/d) = ad/bc if $b, c, d \neq 0$

*The Order Axioms*

This group of axioms has to do with a concept which establishes an ordering among the real numbers. We introduce the order properties as a set of axioms about a new undefined concept called positiveness and then define terms like less than and greater than in terms of positiveness. 

We assume there exists a certain subset $R^{+} \psubset R$ called the set of positive real numbers which satisfies the following 3 order axioms: 

*** Axiom 7: If x and y are in $R^+$, so are x + y and xy
*** Axiom 8: For every real $x \neq 0$, either $x \in R^+$ or $-x \in R^+$, but not both
*** Axiom 9: $0 \nin R^+$

Now we can define the symbols <, >, leq and geq 

*** x < y means that y - x  is positive 
*** y > x means that x < y 
*** x \leq y means that either x < y or x = y 
*** x \geq y means that y \leq x

From the order axioms, we can derive all the usual rules for calculating with inequalities

*** Theorem 1.16: Trichotomy Law: For arbitrary real numbers a and b, exactly one of the three relations a < b, b < a, a = b holds
*** Theorem 1.17: Transitive Law: If a < b and b < c, then a < c 
*** Theorem 1.18: If a < b, then a + c < b + c 
*** Theorem 1.19: If a < b and c > 0, then ac < bc 
*** Theorem 1.20: If $a /neq 0$, then $a^2 > 0$
*** Theorem 1.21: 1 > 0
*** Theorem 1.22: If a < b and c < 0, then ac > bc 
*** Theorem 1.23: If a < b, then -a > -b. In particular, if a < 0, then -a > 0
*** Theorem 1.24: If ab > 0, then both a and b are positive or both are negative 
*** Theorem 1.25: If a < b and c < d, then a + c < b + d 

*Integers and Rational Numbers*
*** Definition: Inductive Set

A set of real numbers is called an inductive set if it has the following two properties: 

1. The number 1 is in the set
2. For every x in the set, the number x + 1 is also in the set 

*** Definition: Positive Integers 

A real number is called a positive integer if it belongs to every inductive set 

*Upper bound of a set, maximum element, least upper bound (supremum)*

*** Definition: Least Upper Bound 

A number B is called a least upper bound of a nonempty set S if B has the following two properties:

1. B is an upper bound for S
2. No number less than B is an upper bound for S 

*** Theorem 1.26: Two different numbers cannot be least upper bounds for the same set  

It is common practice to refer to the least upper bound of a set by the more concise term supremum and write B = sup S

*** Axiom 10: Every nonempty set S of real numbers which is bounded above has a supremum; that is, there is a real number B such that B = sup S


*** Definition: Greatest Lower Bound

A number L is called a greatest lower bound (or infimum) of S if 

1. L is a lower bound for S
2. No number greater than L is a lower bound for S

*** Theorem 1.27: Every nonempty set S that is bounded below has a greatest lower bound; that is, there is a real number L such that L = inf S

*The Archimedean Property of the Real-Number System*

*** Theorem 1.28: The set P of positive integers 1, 2, 3, ... is unbounded above

*** Theorem 1.29: For every real x there exists a positive integer n such that n > x 

*** Theorem 1.30: If x > 0 and if y is an arbitrary real number, there exists a positive integer n such that nx > y

*** Theorem 1.31: If three real numbers a, x, and y satisfy the inequalities $a \leq x \leq a + \frac{y}{n}$ for every integer $n \geq 1$, then $x = a$

*Fundamental Properties of the Supremum and Infimum*

*** Theorem 1.32: 

Let h be a given positive number and let S be a set of real numbers. 

a. If S has a supremum, then for some x in S we have x > sup S - h
b. If S has an infimum, then for some x in S we have x < inf S + h

*** Theorem 1.33: Additive Property

Given nonempty subsets A and B of R, let C denote the set $C = \{a + b | a \in A, b \in B \}$

a. If each of A and B has a supremum, then C has a supremum, and sup C = sup A + sup B
b. If each of A and B has an infimum, then C has an infimum, and inf C = inf A + inf B 

*** Theorem 1.34: Given two nonempty subsets S and T of R such that $s \leq t$ for every s in S and every t in T. Then S has a supremum, and T has an infimum, and they satisfy the inequality $sup S \leq inf T$

*Existence of Square Roots of Nonnegative Real Numbers*

*** Theorem 1.35:

Every nonnegative real number a has a unique nonnegative square root 

** Part 4. Mathematical Induction, Summation Notation, and Related Topics 

*** Theorem 1.36: Principle of Mathematical Induction

Let S be a set of positive integers which has the following two properties: 

1. The number 1 is in the set S
2. If an integer k is in S, then so is k + 1 

Then every positive integer is in the set S. 

*** Theorem 1.37: The Well-Ordering Principle 

Every nonempty set of positive integers contains a smallest member 

*Summation Notation*

*Absolute Values and the Triangle Inequality*

*** Theorem 1.38: If $a \geq 0$, then $|x| \leq a$ if and only if $-a \leq x \leq a$

*** Theorem 1.39: Triangle Inequality: 

For arbitrary real numbers x and y, we have $|x + y| \leq |x| + |y|$

If we take x = a - c and y = c - b, then x + y = a - b and the triangle inequality becomes $|a - b| \leq |a - c| + |b - c|$

*** Theorem 1.40

For arbitrary real numbers a_1, a_2, ..., a_n we have 

$|\sum_{k = 1}^n a_k| \leq \sum_{k = 1}^n |a_k|$

*** Theorem 1.41: The Cauchy-Schwarz Inequality 

If $a_1, ..., a_n$ and $b_1, ..., b_n$ are arbitrary real numbers, we have 

$(\sum_{k = 1}^n a_k b_k)^2 \leq (\sum_{k = 1}^n a_k^2)(\sum_{k = 1}^n b_k^2)$

on miscellaneous exercises involving induction 

on exercise 4b
