* Calculus Vol 1

* Introduction
** Part 1. Historical Introduction 

Integral calculus deals with the problem of area. Differential calculus deals with the problem of tangents. 

This section is mainly interested in showing the archimedean construction of the integral applied to a parabola. The exercises have you derive more general integrals of functions

** Part 2. Some Basic Concepts of the Theory of Sets

*** Definition | Set Equality 

Two sets $A$ and $B$ are said to be equal (or identical) if they consist of exactly the same elements, in which case we write $A = B$. If one of the sets contains an element not in the other, we say the sets are unequal and write $A \neq B$.


*** Definition | Subset

A set $A$ is said to be a subset of a set $B$, and we write $A \subset B$ whenever every element of $A$ also belongs to $B$. We say that $A$ is contained in $B$, or that $B$ contains $A$. The relation $\psubset$ is referred to as set inclusion.

To help simplify the language, we call a collection of sets a class. Capital script letters like $\mathcal{A}, \mathcal{B}, \mathcal{C}, ...$ are used to denote classes. 

** Part 3. A Set of Axioms for the Real-Number System 

The axioms we list here fall in a natural way into three groups which we can refer to as field axioms, order axioms, and the least upper bound axiom. 

**The Field Axioms**

*** Axiom 1: Commutative Laws: x + y = y + x 
*** Axiom 2: Associative Laws: x + (y + z) = (x + y) + z
*** Axiom 3: Distributive Law: x(y + z) = xy + xz
*** Axiom 4: Existence of Identity Elements: There exist two distinct real numbers, which we denote by 0 and 1, such that for every real x we have x + 0 = x and 1 * x = x 
*** Axiom 5: Existence of Negatives: For every real number x there is a real number y such that x + y = 0 
*** Axiom 6: Existence of Reciprocals: For every real number $x /neq 0$ there is a real number y such that $xy = 1$ 

From the above axioms, we can deduce all the usual laws of elementary algebra. The most important of these laws are collected below as a list of theorems.

*** Theorem 1.1: Cancellation Law for Addition: If a + b = a + c, then b = c
*** Theorem 1.2: Possibility of Subtraction: Given a and b, there is exactly one x such that a + x = b. This x is denoted by b - a. In particular, 0 - a is written simply -a and is called the negative of a. 
*** Theorem 1.3: b - a = b + (-a)
*** Theorem 1.4: -(-a) = a 
*** Theorem 1.5: a(b - c) = ab - ac 
*** Theorem 1.6: 0*a = a*0 = 0 
*** Theorem 1.7: Cancellation Law for Multiplication: If ab = ac and $a /neq 0$, then b = c. In particular, this shows that the number 1 of axiom 4 is unique. 
*** Theorem 1.8: Possibility of Division: Given a and b with $a \neq 0$, there is exactly one x such that $ax = b$. This x is denoted by b/a, and is called the quotient of b and a. In particular, 1/a is also written $a^{-1}$ and is called the reciprocal of a
*** Theorem 1.9: If $a \neq 0$, then b/a = b * $a^{-1}$
*** Theorem 1.10: If $a \neq 0$, then $(a^{-1})^{-1} = a$ 
*** Theorem 1.11: If ab = 0, then a = 0 or b = 0
*** Theorem 1.12: (-a)b = -(ab) and (-a)(-b) = ab 
*** Theorem 1.13: (a/b) + (c/d) = (ad + bc)/(bd) if $b, d /neq 0$
*** Theorem 1.14: (a/b)(c/d) = ac/bd if $b, d \neq 0$ 
*** Theorem 1.15: (a/b)/(c/d) = ad/bc if $b, c, d \neq 0$

*The Order Axioms*

This group of axioms has to do with a concept which establishes an ordering among the real numbers. We introduce the order properties as a set of axioms about a new undefined concept called positiveness and then define terms like less than and greater than in terms of positiveness. 

We assume there exists a certain subset $R^{+} \psubset R$ called the set of positive real numbers which satisfies the following 3 order axioms: 

*** Axiom 7: If x and y are in $R^+$, so are x + y and xy
*** Axiom 8: For every real $x \neq 0$, either $x \in R^+$ or $-x \in R^+$, but not both
*** Axiom 9: $0 \nin R^+$

Now we can define the symbols <, >, leq and geq 

*** x < y means that y - x  is positive 
*** y > x means that x < y 
*** x \leq y means that either x < y or x = y 
*** x \geq y means that y \leq x

From the order axioms, we can derive all the usual rules for calculating with inequalities

*** Theorem 1.16: Trichotomy Law: For arbitrary real numbers a and b, exactly one of the three relations a < b, b < a, a = b holds
*** Theorem 1.17: Transitive Law: If a < b and b < c, then a < c 
*** Theorem 1.18: If a < b, then a + c < b + c 
*** Theorem 1.19: If a < b and c > 0, then ac < bc 
*** Theorem 1.20: If $a /neq 0$, then $a^2 > 0$
*** Theorem 1.21: 1 > 0
*** Theorem 1.22: If a < b and c < 0, then ac > bc 
*** Theorem 1.23: If a < b, then -a > -b. In particular, if a < 0, then -a > 0
*** Theorem 1.24: If ab > 0, then both a and b are positive or both are negative 
*** Theorem 1.25: If a < b and c < d, then a + c < b + d 

*Integers and Rational Numbers*
*** Definition: Inductive Set

A set of real numbers is called an inductive set if it has the following two properties: 

1. The number 1 is in the set
2. For every x in the set, the number x + 1 is also in the set 

*** Definition: Positive Integers 

A real number is called a positive integer if it belongs to every inductive set 

*Upper bound of a set, maximum element, least upper bound (supremum)*

*** Definition: Least Upper Bound 

A number B is called a least upper bound of a nonempty set S if B has the following two properties:

1. B is an upper bound for S
2. No number less than B is an upper bound for S 

*** Theorem 1.26: Two different numbers cannot be least upper bounds for the same set  

It is common practice to refer to the least upper bound of a set by the more concise term supremum and write B = sup S

*** Axiom 10: Every nonempty set S of real numbers which is bounded above has a supremum; that is, there is a real number B such that B = sup S


*** Definition: Greatest Lower Bound

A number L is called a greatest lower bound (or infimum) of S if 

1. L is a lower bound for S
2. No number greater than L is a lower bound for S

*** Theorem 1.27: Every nonempty set S that is bounded below has a greatest lower bound; that is, there is a real number L such that L = inf S

*The Archimedean Property of the Real-Number System*

*** Theorem 1.28: The set P of positive integers 1, 2, 3, ... is unbounded above

*** Theorem 1.29: For every real x there exists a positive integer n such that n > x 

*** Theorem 1.30: If x > 0 and if y is an arbitrary real number, there exists a positive integer n such that nx > y

*** Theorem 1.31: If three real numbers a, x, and y satisfy the inequalities $a \leq x \leq a + \frac{y}{n}$ for every integer $n \geq 1$, then $x = a$

*Fundamental Properties of the Supremum and Infimum*

*** Theorem 1.32: 

Let h be a given positive number and let S be a set of real numbers. 

a. If S has a supremum, then for some x in S we have x > sup S - h
b. If S has an infimum, then for some x in S we have x < inf S + h

*** Theorem 1.33: Additive Property

Given nonempty subsets A and B of R, let C denote the set $C = \{a + b | a \in A, b \in B \}$

a. If each of A and B has a supremum, then C has a supremum, and sup C = sup A + sup B
b. If each of A and B has an infimum, then C has an infimum, and inf C = inf A + inf B 

*** Theorem 1.34: Given two nonempty subsets S and T of R such that $s \leq t$ for every s in S and every t in T. Then S has a supremum, and T has an infimum, and they satisfy the inequality $sup S \leq inf T$

*Existence of Square Roots of Nonnegative Real Numbers*

*** Theorem 1.35:

Every nonnegative real number a has a unique nonnegative square root 

** Part 4. Mathematical Induction, Summation Notation, and Related Topics 

*** Theorem 1.36: Principle of Mathematical Induction

Let S be a set of positive integers which has the following two properties: 

1. The number 1 is in the set S
2. If an integer k is in S, then so is k + 1 

Then every positive integer is in the set S. 

*** Theorem 1.37: The Well-Ordering Principle 

Every nonempty set of positive integers contains a smallest member 

*Summation Notation*

*Absolute Values and the Triangle Inequality*

*** Theorem 1.38: If $a \geq 0$, then $|x| \leq a$ if and only if $-a \leq x \leq a$

*** Theorem 1.39: Triangle Inequality: 

For arbitrary real numbers x and y, we have $|x + y| \leq |x| + |y|$

If we take x = a - c and y = c - b, then x + y = a - b and the triangle inequality becomes $|a - b| \leq |a - c| + |b - c|$

*** Theorem 1.40

For arbitrary real numbers a_1, a_2, ..., a_n we have 

$|\sum_{k = 1}^n a_k| \leq \sum_{k = 1}^n |a_k|$

*** Theorem 1.41: The Cauchy-Schwarz Inequality 

If $a_1, ..., a_n$ and $b_1, ..., b_n$ are arbitrary real numbers, we have 

$(\sum_{k = 1}^n a_k b_k)^2 \leq (\sum_{k = 1}^n a_k^2)(\sum_{k = 1}^n b_k^2)$

* 1. The Concepts of Integral Calculus
:PROPERTIES:
:header-args: :session R-session :results output value table :colnames yes
:END:


#+NAME: round-tbl
#+BEGIN_SRC emacs-lisp :var tbl="" fmt="%.1f"
(mapcar (lambda (row)
          (mapcar (lambda (cell)
                    (if (numberp cell)
                        (format fmt cell)
                      cell))
                  row))
        tbl)
#+end_src

#+RESULTS: round-tbl

This chapter presents the Integral and some of its basic properties. In order to do this, we must have some acquaintance with functions. 

** The Basic Ideas of Cartesian Geometry 

The x coordinate of a point is sometimes called its abscissa and the y coordinate its ordinate. 

** Functions. Informal Description and Examples 

Today, the meaning of function is essentially this: Given two sets, X and Y, a function is a correspondence which associates with each element of X one element, and only one element of Y. In this example, X is the domain and Y is the range of the function. 

In calculus, we are primarily interested in functions whose domain and range are real numbers.

#+BEGIN_SRC R :file plot.svg :results graphics file
library(tidyverse)
library(pipeR)
library(patchwork)

identity_f <- function(x) x
abs_f <- function(x) abs(x)
factorial_f <- function(x) factorial(x)

reals <- seq(from = -10, 10, by = 1)
small_reals <- seq(-2.5, 2.5, .5)

plot_function <- function(fun, title = "", domain = reals) {
    require(latex2exp)
    domain %>%
        enframe() %>%
        ggplot() +
        geom_hline(yintercept = 0, alpha = 0.5) +
        geom_vline(xintercept = 0, alpha = 0.5) +
        geom_line(aes(x = value, y = fun(value)), color = "mediumpurple", lty = 1) +
        xlab("X") + ylab("Y") +
        ggdark::dark_theme_gray() +
        ggtitle(TeX(title))
}

# restricted domain factorial
plot_function(factorial_f, title = "f(x) = x!", domain = seq(from = 0, 10, by = 1)) -> p_fact

list("f(x) = x" = identity_f,
     "f(x) = |x|" = abs_f) %>%
    imap(., ~ plot_function(fun = .x, title = .y)) %>%
    append(list(p_fact)) %>% 
    reduce(`/`) 
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

Here are some properties of the absolute value function: 

1. $f(-x) = f(x)$
2. $f(x^2) = x^2$
3. $f(x + y) \leq f(x) + f(y)$
4. $f(f(x)) = f(x)$
5. $f(x) = \sqrt(x^2)$

** Functions. Formal Definition as a Set of Ordered Pairs 

*** Definition: Function

A function f is a set of ordered pairs (x, y) no two of which have the same first member 

It is customary to write $y = f(x)$ instead of $(x, y) \in f$ to indicate that the pair $(x, y)$ is in the set $f$

*** Theorem 1.1

Two functions f and g are equal iff
1. f and g have the same domain
2. f(x) = g(x) for every x in the domain of f 

** More Examples of Real Functions

#+BEGIN_SRC R :file plot.svg :results graphics file
constant_f <- function(x, c) c
constant_3 <- partial(constant_f, c = 3)
constant_3(1234)

linear_f <- function(x, a, b) a*x + b
linear_2x_1_f <- partial(linear_f, a = 2, b = -1)
linear_2x_1_f(2)

power_f <- function(x, power) x^power
power_2 <- partial(power_f, 2)
power_f(reals, 3)

polynomial_f <- function(x, degree, coefficients) {
    raise_f <- function(x) {
        x^(1:4)
    }
    map_dbl(x, ~ sum(rev(raise_f(.x)) * coefficients))
}
polynomial_ex <- partial(polynomial_f, degree = 4, coefficients = c((1/2), 0, -2, 0))

circle_f <- function(x, r) {
    if (abs(x) < r) sqrt(r^2 - x^2)
    else 0
}

circle_f <- function(x, r) {
    f <- function(x, r) sqrt(r^2 - x^2)
    g <- function(x, r) (-1) * sqrt(r^2 - x^2)
    
    x %>%
        enframe() %>%
        list(mutate(., output = f(value, r)),
             mutate(., output = g(value, r))) %>%
        rlist::list.skip(1) %>%
        bind_rows()
}

## circle plot
seq(-3.5, 3.5, 0.1) %>%
    circle_f(r = 3) %>%
    ggplot(aes(x = value, y = output)) +
    geom_point(alpha = 0.3) +
    geom_line(color = "mediumpurple") +
    ggtitle(TeX("Circle : y = +- \\sqrt{r^2 - x^2}")) +
    ggdark::dark_theme_gray() -> c_plot

## sum of functions plot
seq(-3.5, 3.5, 0.1) %>%
    enframe() %>%
    mutate(output_f = value * value) %>% 
    mutate(output_g = value * value * value) %>%
    mutate(output_sum = output_f + output_g) %>% 
    ggplot() +
    geom_line(aes(x = value, y = output_f), color = "mediumpurple") +
    geom_line(aes(x = value, y = output_g), color = "blue") +
    geom_line(aes(x = value, y = output_sum), color = "forestgreen") +
    ggtitle(TeX("Sum of Functions: f(x) = x^2 + g(x) = x^3")) +
    ggdark::dark_theme_gray() -> s_plot


list("Constant : f(x) = 3" = constant_3,
     "Linear : f(x) = 2x -1" = linear_2x_1_f,
     "Power : f(x) = x^2" = power_2,
     "Polynomial : f(x) = \\frac{1}{2} x^4 - 2 x^2" = polynomial_ex) %>%
    imap(~ plot_function(.x, .y, domain = small_reals)) %>%
    append(list(c_plot)) %>%
    append(list(s_plot)) %>% 
    reduce(`+`)
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

Exercise 6. 

#+BEGIN_SRC R :file plot.svg :results graphics file
f_fun <- function(x) {
    if (between(x, 0, 1)) 1
    else if (x > 1 & x <= 2) 2
    else 0
}

plot_function <- function(fun, title = "", domain = reals) {
    require(latex2exp)
    domain %>%
        enframe() %>%
        mutate(fun_out = flatten_dbl(map(value, f_fun))) %>>%
        (~ tbl) %>% 
        ggplot(aes(x = value, y = fun_out)) +
        geom_hline(yintercept = 0, alpha = 0.5) +
        geom_vline(xintercept = 0, alpha = 0.5) %>>%
        (~ base_plot) +
        geom_point(color = "mediumpurple") +
        geom_step(color = "forestgreen", lty = 3) +
        xlab("X") + ylab("Y") +
        ggdark::dark_theme_gray() +
        ggtitle(TeX(title))
}

## draw the graph of f
plot_function(f_fun, domain = small_reals)
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

On problem 6

#+BEGIN_SRC R :file plot.svg :results graphics file
## let g(x) = f(2x)
p1 <- plot_function(f_fun, domain = small_reals) + ggtitle("x") + xlim(0, 2)
p2 <- plot_function(f_fun, domain = (2 * small_reals)) + ggtitle("2x") + xlim(0, 2)
p3 <- plot_function(f_fun, domain = (small_reals - 2)) + ggtitle("x - 2") + xlim(0, 5)
p4 <- plot_function(f_fun, domain = ((small_reals * 2) + (small_reals - 2))) + ggtitle("f(2x) + f(x - 2)") + xlim(0, 5)

p1 / p2 / p3 / p4
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

#+BEGIN_SRC R :file plot.svg :results graphics file
small_reals %>%
    enframe() %>% 
    ggplot() +
    geom_line(aes(x = value, y = value), color = "forestgreen") +
    geom_line(aes(x = value, y = value * value * value), color = "mediumpurple") +
    geom_point(data = tribble(~ value, ~ out, 0, 0, -1, -1, 1, 1), aes(x = value, y = out), color = "white", shape = 1, size = 5) +
    ggdark::dark_theme_gray() +
    ggtitle("Intersection of f(x) = x and f(x) = x^3")
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

#+BEGIN_SRC R :file plot.svg :results graphics file
small_reals %>%
    enframe() %>% 
    ggplot() +
    geom_line(aes(x = value, y = (value * value - 2)), color = "forestgreen") +
    geom_line(aes(x = value, y = (2 * (value * value) + 4 * value + 1)), color = "mediumpurple") +
    geom_point(data = tribble(~ value, ~ out, -1, -1), aes(x = value, y = out), color = "white", shape = 1, size = 5) +
    ggdark::dark_theme_gray() +
    ggtitle("Intersection of f(x) = x^2 - 2 and g(x) = 2x^2 + 4x + 1")
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

** The Concept of Area as a Set Function

When we assign an area to a plane region, we associate a number with a set S in the plane. This means that we have a function a (an area function) which assigns a real number a(S) (the area of S) to each set S in some given collection of sets. A function of this kind, whose domain is a collection of sets and whose function values are real numbers, is called a set function. The basic problem is this: Given a plane set S, what area a(S) shall we assign to S? 

*** Axiomatic Definition of Area: 

We assume that there exists a class $\mathcal{M}$ of measurable sets in the plane and a set function $a$, whose domain is $\mathcal{M}$, with the following properties: 

1. Non-negative Property: For each set $S$ in $\mathcal{M}$, we have $a(S) \geq 0$
2. Additive Property: If $S$ and $T$ are in $\mathcal{M}$, then $S \cup T$ and $S \cap T$ are in $\mathcal{M}$, and we have $a(S \cup T) = a(S) + a(T) - a(S \cap T)$
3. Difference Property: If $S$ and $T$ are in $\mathcal{M}$, with $S \subseteq T$, then $T - S$ is in $\mathcal{M}$, and we have $a(T - S) = a(T) - a(S)$
   3.b: Monotone Property: Since $a(T - S) \geq 0$, $a(S) \leq a(T)$ for $S, T \in \mathcal{M}$ with $S \subseteq T$. 
4. Invariance Under Congruence: If a set $S$ is in $\mathcal{M}$ and it $T$ is congruent to $S$, then $T$ is also in $\mathcal{M}$ and we have $a(S) = a(T)$
5. Choice of Scale: Every rectangle $R$ is in $\mathcal{M}$. If the edges of $R$ have lengths $h$ and $k$, then $a(R) = hk$.
6. Exhaustion Property: Let $Q$ be a set that can be enclosed between two step regions $S$ and $T$, so that $S \subseteq Q \subseteq T$. If there is one and only one number $c$ which satisfies the inequalities $a(S) \leq c \leq a(T)$ for all step regions $S$ and $T$, then $Q$ is measurable and $a(Q) = c$. 

** Intervals and Ordinate Sets

Let $f$ be a nonnegative function whose domain is a closed interval $[a, b]$. The portion of the plane between the graph of $f$ and the x-axis is called the ordinate set of $f$. Ordinate sets are the geometric object whose areas we want to compute by means of the integral calculus. 

** Partitions and Step Functions 

*** Definition: Step Function

A function $s$, whose domain is a closed interval $[a, b]$, is called a step function if there is a partition $P = \{x_0, x_1, ..., x_n\}$ of $[a, b]$ such that $s$ is constant on each open subinterval of $P$. That is to say, for each $k = 1, 2, ..., n$ there is a real number $s_k$ such that $s(x) = s_k$ if $x_{k - 1} < x < x_k$

Note: At each of the endpoints $x_{k-1}$ and $x_k$ the function must have some well-defined value, but this need not be the same as $s_k$. 

For a given partition $P$ of $[a, b]$, we can always form a new partition $P'$ by adjoining more subdivision points to those already in $P$. Such a partition $P'$ is called a refinement of $P$ and is said to be finer than $P$. If a function is constant on the open subintervals of $P$, then it is also constant on the open subintervals of every refinement $P'$. 

** Sum and Product of Step Functions

New step functions may be formed from given step functions by adding corresponding function values. To show that $u$ is actually a step function, we must exhibit a partition $P$ such that $u$ is constant along the open subintervals of $P$. For the new partition $P$, we take all the points of $P_1$ along with $P_2$. This partition, $P_1 \cup P_2$ is called the common refinement of $P_1$ and $P_2$. 


#+BEGIN_SRC R :file plot.svg :results graphics file
library(tidyverse)
library(patchwork)

f <- function(x) {
    floor(x)
}

plot_sf <- function(domain, fun) {
    domain %>%
        enframe() %>%
        mutate(y_val = fun(value)) %>% 
        ggplot(aes(x = value, y = y_val)) +
        geom_step(direction = "h") +
        scale_x_continuous(breaks = 0:10)
}

plot_sf(seq(0, 10, 0.1), function(x) f(sqrt(x))) +
    ggtitle(latex2exp::TeX("$\\floor{\\sqrt{x}}$")) +
    ylim(0, 10) -> p1

plot_sf(seq(0, 10, 0.1), function(x) sqrt(f(x))) +
    ggtitle(latex2exp::TeX("$\\sqrt{f(x)}$")) +
    ylim(0, 10) -> p2

plot_sf(seq(0, 3, 0.1), function(x) f(x*x)) +
    ggtitle(latex2exp::TeX("$\\f{x^2}$")) +
    ylim(0, 10) -> p3

plot_sf(seq(0, 3, 0.1), function(x) f(x) * f(x)) +
    ggtitle(latex2exp::TeX("$\\floor{x}^2$")) +
    ylim(0, 10) -> p4

p1 + p2 + p3 + p4
#+END_SRC

#+RESULTS:
[[file:plot.svg]]

on 4d
