* Calculus Vol 1

* Introduction 

** Part 1. Historical Introduction 

Integral calculus deals with the problem of area. Differential calculus deals with the problem of tangents. 

This section is mainly interested in showing the archimedean construction of the integral applied to a parabola. The exercises have you derive more general integrals of functions

** Part 2. Some Basic Concepts of the Theory of Sets

*** Definition | Set Equality 

Two sets $A$ and $B$ are said to be equal (or identical) if they consist of exactly the same elements, in which case we write $A = B$. If one of the sets contains an element not in the other, we say the sets are unequal and write $A \neq B$.


*** Definition | Subset

A set $A$ is said to be a subset of a set $B$, and we write $A \subset B$ whenever every element of $A$ also belongs to $B$. We say that $A$ is contained in $B$, or that $B$ contains $A$. The relation $\psubset$ is referred to as set inclusion.

To help simplify the language, we call a collection of sets a class. Capital script letters like $\mathcal{A}, \mathcal{B}, \mathcal{C}, ...$ are used to denote classes. 

** Part 3. A Set of Axioms for the Real-Number System 

The axioms we list here fall in a natural way into three groups which we can refer to as field axioms, order axioms, and the least upper bound axiom. 

**The Field Axioms**

*** Axiom 1: Commutative Laws: x + y = y + x 
*** Axiom 2: Associative Laws: x + (y + z) = (x + y) + z
*** Axiom 3: Distributive Law: x(y + z) = xy + xz
*** Axiom 4: Existence of Identity Elements: There exist two distinct real numbers, which we denote by 0 and 1, such that for every real x we have x + 0 = x and 1 * x = x 
*** Axiom 5: Existence of Negatives: For every real number x there is a real number y such that x + y = 0 
*** Axiom 6: Existence of Reciprocals: For every real number $x /neq 0$ there is a real number y such that $xy = 1$ 

From the above axioms, we can deduce all the usual laws of elementary algebra. The most important of these laws are collected below as a list of theorems.

*** Theorem 1.1: Cancellation Law for Addition: If a + b = a + c, then b = c
*** Theorem 1.2: Possibility of Subtraction: Given a and b, there is exactly one x such that a + x = b. This x is denoted by b - a. In particular, 0 - a is written simply -a and is called the negative of a. 
*** Theorem 1.3: b - a = b + (-a)
*** Theorem 1.4: -(-a) = a 
*** Theorem 1.5: a(b - c) = ab - ac 
*** Theorem 1.6: 0*a = a*0 = 0 
*** Theorem 1.7: Cancellation Law for Multiplication: If ab = ac and $a /neq 0$, then b = c. In particular, this shows that the number 1 of axiom 4 is unique. 
*** Theorem 1.8: Possibility of Division: Given a and b with $a \neq 0$, there is exactly one x such that $ax = b$. This x is denoted by b/a, and is called the quotient of b and a. In particular, 1/a is also written $a^{-1}$ and is called the reciprocal of a
*** Theorem 1.9: If $a \neq 0$, then b/a = b * $a^{-1}$
*** Theorem 1.10: If $a \neq 0$, then $(a^{-1})^{-1} = a$ 
*** Theorem 1.11: If ab = 0, then a = 0 or b = 0
