#+TITLE: The Logarithm, The Exponential, and the Inverse Trigonometric Functions

* Introduction

$u = \log_b x$ means $x = b^u$

$\log_b xy = \log_b x + \log_b y$

* Motivation for the Definition of the Natural Logarithm as an Integral

When a mathematician tries to formulate a definition of a concept, such as the logarithm, they usually have in mind a number of properties they want the concept to posess. 
By examining these properties, they are often led to a simple formula or process that might serve as a definition from which all the desired properties spring forth as logical deductions

If we think of the logarithm as a function $f$, then we want this function to have the property expressed by the formula: 

$f(xy) = f(x) + f(y)$

whenever $x, y, xy$ are in the domain of $f$. An equation like above, which expresses a relationship between the values of a function at 2 or more points, is called a *functional equation*. 
Many mathematical problems can be reduced to solving a functional equation, a solution being any function which satisfies the equation. 

* The Definition of the Logarithm. Basic Properties

** Definition : Logarithm

If $x$ is a positive real number, we define the natural logarithm of $x$, denoted temporarily by $L(x)$, to be the integral

$L(x) = \int_1^x \frac{1}{t} dt$

when $x > 1$

** Theorem 6.1

The logarithm has the following properties:

a. $L(1) = 0$
b. $L'(x) = \frac{1}{x}$ for every $x > 0$
c. $L(ab) = L(a) + L(b)$ for every $a, b > 0$

* The Graph of the Natural Logarithm

Some more properties deduced from 6.1: 

- L has a positive derivative everywhere, so it is strictly increasing on every interval
- Since L(1) = 0, the graph lies above the x axis if x > 1, and below is 0 < x < 1
- For x > 1, the slope gradually decreases toward 0 as x increases indefinitely
- For small values of x, the slope is large, and it increases without bound as x decreases towards 0
- The second derivative is $L''(x) = -\frac{1}{x^2}$, which is negative for all x, so $L$ is a concave function

* Consequences of the Functional Equation $L(ab) = L(a) + L(b)$

The logarithm is unbounded above. For every positive number $M$, there exists values of $x$ such that $L(x) > M$

This leads us to the more general formula $L(a^n) = n L(a)$ for every $n \geq 1$. 

** Theorem 6.2

For every real number $b$ there is exactly one positive real number $a$ whose logarithm $L(a) = b$

** Definition

We denote by $e$ that number for which $L(e) = 1$

Natural logarithms are also called *Napierian Logarithms*, in honor of their inventor John Napier. It is common practice to use the symbols $\ln x$ or $\log x$ instead of $L(x)$ to denote the logarithm of $x$

* Logarithms Referred to Any Positive Base $b \neq 1$

** Definition 

If $b > 0$, $b \neq 1$, and if $x > 0$, the logarithm of $x$ to the base $b$ is the number $\log_b (x) = \frac{\ln x}{\ln b}$

* Differentiation and Integration Formulas involving Logarithms

If $u = f(x)$ where $f$ has a continuous derivative, we have

$\int \frac{du}{u} = \log u + C$ or $\int \frac{f'(x)}{f(x)} dx = \log f(x) + C$

These are only valid if $u$ or $f(x)$ is positive since the logarithm is not defined for negative numbers

We can extend the range of validity of these formulas to accomodate functions that are negative or positive (but nonzero) by introducing a new function:

$L_0(x) = \log |x| = \int_1^{|x|} \frac{1}{t} dt$

$L_0(xy) = L_0(x) + L_0(y)$ for all real $x \neq 0$

$L_0'(x) = \frac{1}{x}$

If we use $L_0$ instead of $L$ in the foregoing integration formulas, we can extend their scope to include functions which assign negative values as well as positive values.

We can generalize the above as:

$\int \frac{du}{u} = \log |u| + C$ or $\int \frac{f'(x)}{f(x)} dx = \log |f(x)| + C$

* Logarithmic Differentiation

Suppose we form a composition of $L_0$ with any differentiable function $f$; say

$g(x) = L_0[f(x)] = \log |f(x)|$

for those $x \neq 0$. The chain rule yields:

$g'(x) = L_0'[f(x)]f'(x) = \frac{f'(x)}{f(x)}$

* Polynomial Approximations to the Logarithm

In this section, we show that the logarithm function can be approximated by certain polynomials which can be used to compute logarithms to any desired degree of accuracy.

** Theorem 6.3 

Let $P_n$ denote the polynomial of degree $n$ given by $P_n(x) = x + \frac{x^2}{2} + \frac{x^3}{3} + ... + \frac{x^n}{n} = \sum_{k=1}^n \frac{x^k}{k}$

Then, for every $x < 1$ and every $n \geq 1$, we have

$-\log(1-x) = P_n(x) + \int_0^x \frac{u_n}{1 - u} du$

We can also write this as $-log(1-x) = P_n(x) + E_n(x)$ where $E_n(x) = \int_0^x \frac{u_n}{1 - u}$ represents the error made when we approximate $-log(1-x)$ by the polynomial $P_n(x)$. 

To use this in computations, we need to know whether the error is positive or negative and how large it can be. The next theorem tells us that for small positive $x$ the error $E_n(x)$ is positive, but for negative $x$ the error has the same sign as $(-1)^{n + 1}$, where $n$ is the degree of the approximating polynomial. It also gives useful upper and lower bounds. 

** Theorem 6.4

If $0 < x < 1$ we have the inequalities

$\frac{x^{n + 1}}{n + 1} \leq E_n(x) \leq \frac{1}{1 - x} \frac{x^{n + 1}}{n + 1}$

If $x < 0$, the error $E_n(x)$ has the same sign as $(-1)^{n + 1}$ and we have 

$0 < (-1)^{n + 1}E_n(x) \leq \frac{|x|^{n + 1}}{n + 1}$

** Theorem 6.5

This theorem gives a formula which is admirably suited for computations of logarithms

if $0 < x < 1$ and if $m \geq 1$, we have

$\log \frac{1 + x}{1 - x} = 2(x + \frac{x^3}{3} + ... + \frac{x^{2m - 1}}{2m - 1}) + R_m(x)$

where the error term $R_m(x)$ satisfies the inequalities

$\frac{x^{2m + 1}}{2m + 1} < R_m(x) \leq \frac{2 - x}{1 - x} \frac{x^{2m + 1}}{2m + 1}$

* Exercises


#+BEGIN_SRC R
library(tidyverse)

get_log_approx <- function(x, m) {
    get_rm_interval <- function() {
        o <- x^(2 * m + 1) / (2 * m + 1)
        list(o, ((2 - x) / (1 - x)) * o)
    }

    ldom <- (1 + x) / (1 - x)
    exponents <- seq(from = 1, to = 2 * m - 1, by = 2)
    main <- (x^exponents) / exponents

    log_name <- glue::glue("log({ldom})")

    list(sum(2 * main), get_rm_interval()) %>%
        set_names(c(log_name, "Error Bound"))
}

## exercise 1: log 2
get_log_approx(1/3, 5)

## exercise 2: log 3 - log 2
get_log_approx(1/3, 5)[[1]]

## exercise 2: log 3
get_log_approx(1/5, 5)[[1]] + get_log_approx(1/3, 5)[[1]]

## 2 < e < 3

## exercise 3:
## log 5 - log(4) = log(5) - 2log(2)
## log 5
get_log_approx(1/9, 5)[[1]] + 2 * get_log_approx(1/3, 5)[[1]]

## exercise 4:
## log 7 - log 5
## log 7
get_log_approx(1/6, 5)[[1]] +
    get_log_approx(1/9, 5)[[1]] + 2 * get_log_approx(1/3, 5)[[1]]

## calculate a short table listing log n for n = 2, 3, ..., 10

## first make a function to invert
get_desired_x <- function(x) {
    (x - 1) / (x + 1)
}

## log 2
get_log_approx(get_desired_x(2), 5)

map(1:100, ~ {.x %>%
                 get_desired_x() %>%
                 get_log_approx(m = 5) %>%
                 purrr::pluck(1)}) %>%
    set_names(1:100 %>% paste0("log(", ., ")")) %>%
    enframe(name = "symbol",
            value = "value") %>%
    unnest(cols = "value") %>%
    ggplot(aes(x = reorder(symbol, value), y = value, group = NA)) +
    geom_line(color = "mediumpurple") +
    geom_point() +
    theme(axis.text.x = element_text(angle = 90)) +
    xlab("natural log values approximated")
#+END_SRC

* The Exponential Function

Theorem 6.2 shows that for every real $x$ there is 1 and only 1 $y$ such that $L(y) = x$. Therefore, we can use the process of inversion to define $y$ as a function of $x$. 

The resulting inverse function is called the exponential function, or the antilogarithm, and is denoted by $e$.

** Definition

For any real $x$, we define $E(x)$ to be that number $y$ whose logarithm is $x$. That is, $y = E(x)$ means that $L(y) = x$.

** Theorem 6.6

The exponential function has the following properties: 

a. $E(0) = 1$
b. $E'(x) = E(x)$ for every $x$
c. $E(a + b) = E(a)E(b)$ for all $a, b$

go over proofs of b, c again

* Exponentials Expressed as Powers of $e$

$E(r) = e^r$ for $r \in \mathcal{Q}$ 

* The Definition of $e^x$ for arbitrary real $x$

$E(r) = e^r$ for $r \in \mathcal{R}$

One justification for this is to prove the law of exponents: $e^a e^b = e^{a + b}$

* The Definition of $a^x$ for $a > 0$ and $x \in \mathcal{R}$ 

A way we can define $a^x$ is by the formula $a^x = e^{x \log a}$.

This allows us to prove the following properties of exponentials:

- $\log a^x = x \log a$
- $(ab)^x = a^x b^x$
- $a^x a^y = a^{x + y}$
- $(a^x)^y = (a^y)^x = a^{xy}$
- If $a \neq 1$, then $y = a^x$ iff $x = \log_a y$

* Differentiation and Integration Formulas Involving Exponentials

$E'(x) = E(x)$

$\int e^x dx = e^x + C$

$\int a^x = \frac{a^x}{\log(a)} + C$
   
* The Hyperbolic Functions

$\sinh x = \frac{e^x - e^{-x}}{2}$

$\cosh x = \frac{e^x + e^{-x}}{2}$

$\tanh x = \frac{\sinh x}{\cosh x} = \frac{e^x - e^{-x}}{e^x + e^{-x}}$

$\mathrm{csch } x = \frac{1}{\sinh x}$

$\mathrm{sech} x = \frac{1}{\cosh x}$

$\mathrm{coth} x = \frac{1}{\tanh x}$

* Derivatives of Inverse Functions

** Theorem 6.7

Assume $f$ is strictly increasing and continuous on an interval $[a, b]$ and let $g$ be the inverse of $f$. If the derivative $f'(x)$ exists and is nonzero at a point $x \in (a, b)$, then the derivative $g'(y)$ also exists and is nonzero at the corresponding point $y$, where $y = f(x)$. Moreover, the two derivatives are reciprocals of each other: that is $g'(y) = \frac{1}{f'(x)}$

* Inverses of the Trigonometric Functions

$u = \arcsin v$ means $v = \sin u$ and $- \frac{\pi}{2} \leq u \leq \frac{\pi}{2}$

$D \arcsin x = \frac{1}{\sqrt{1 - x^2}}$ if $-1 < x < 1$

$\int_0^x \frac{1}{\sqrt{1 - t^2}} dt = \arcsin x$ if $-1 < x < 1$

$\int \frac{dx}{\sqrt{1 - x^2}} = \arcsin x + C$

$\int \arcsin x dx = x \arcsin x + \sqrt{1 - x^2} + C$

---

$u = \arccos v$ means $v = \cos u$ and $0 \leq u \leq \pi$

$D \arccos x = \frac{-1}{\sqrt{1 - x^2}}$

$\int_0^x \frac{1}{\sqrt{1 - t^2}} dt = \frac{\pi}{2} - \arccos x$ if $-1 < x < 1$

$\int \frac{1}{\sqrt{1 - x^2}} dx = - \arccos x + C$

$\int \arccos x dx = x \arccos x - \sqrt{1 - x^2} + C$

---

$u = \arctan v$ means $v = \tan u$ and $- \frac{\pi}{2} < u < \frac{\pi}{2}$

$D \arctan x = \frac{1}{1 + x^2}$

$\int_0^x \frac{1}{1 + t^2} dt = \arctan x$

$\int \frac{1}{1 + x^2} dx = \arctan x + C$

$\int \arctan x dx = x \arctan x - \frac{1}{2} \log (1 + x^2) + C$

--- 

Inverses:

$\mathrm{arccot} x = \frac{\pi}{2} - \arctan x$ for all $x \in \mathcal{R}$
$\mathrm{arcsec} x = \arccos \frac{1}{x}$ when $|x| \geq 1$
$\mathrm{arccsc} x = \arcsin \frac{1}{x}$ when $|x| \geq 1$

* Integration by Partial Fractions

We shall describe a method for computing the integral of any rational function, and we shall find that the result can always be expressed in terms of polynomials, rational functions, inverse tangents, and logarithms.

The basic idea of the method is to decompose a given rational function into a sum of simpler fractions (called partial fractions) that can be integrated by the techniques discussed earlier. 

We shall describe the general procedure by means of a number of simple examples that illustrate all the essential features of the method:

**Example 1**

If we have two simple fractions that we know how to integrate, we can solve a linear combination of them by decomposition.

i.e., let $Y = \frac{1}{x - 1}$, $Z = \frac{1}{x+3}$. Then $\int 2Y + 3Z = \int \frac{5x + 3}{x^2 + 2x - 3} = 2 \int \frac{1}{x - 1} + 3 \int \frac{1}{x + 3}$

**Example 2**

If we have an integral of the form $\int \frac{ax + b}{x^2 + 2x - 3}$, then we can evaluate it as a linear combination of $Y$ and $Z$ above.

For example, we can write $\frac{2x + 5}{x^2 + 2x - 3} = \frac{A}{x - 1} + \frac{B}{x + 3}$ where $A, B$ are to be determined. We can multiply both sides by $(x-1)(x+3)$ to get $2x+5 = A(x+3) + B(x-1)$.

Then we have two ways to find A, B. The first is to equate coefficients of like powers of $x$, i.e. $A + B = 2$, $3A - B = 5$. Then we can solve for A, B.
Alternatively, we could set $x = 1$, making the $B$ term vanish and solve for $A$, then set $x = -3$ making the $A$ term vanish, then solve for $B$.

The method above also applies to integrals of the form $\int \frac{f(x)}{g(x)} dx$ in which $f$ is a linear polynomial and $g$ is a quadratic polynomial that can be factored into distinct linear factors with real coefficients, say $g(x) = (x - x^1)(x - x^2)$.
In this case, the quotient can be expressed as a linear combination of $\frac{1}{x - x_1}$ and $\frac{1}{x - x_2}$, and integration leads to a corresponding combination of the logarithmic terms $\log|x - x_1|$ and $\log|x - x_2|$. 

The foregoing examples involve rational functions $f/g$ in which the degree of the numerator is less than that of the denominator. A rational function with this property is said to be a proper rational function.
If $f/g$ is improper, that is, the degree of $f$ > deg $g$, then we can express $f/g$ as the sum of a polynomial and a proper rational function. In fact, we simple divide $f$ by $g$ to obtain

$\frac{f(x)}{g(x)} = Q(x) + \frac{R(x)}{g(x)}$

Therefore, there is no loss in generality if we restrict ourselves to proper rational functions.

A general theorem in algebra stats that every proper rational function can be expressed as a finite sum of fractions of the forms $\frac{A}{(x + a)^k}$ and $\frac{Bx + C}{(x^2 + bx + c)^m}$ where $k, m \in \mathcal{N}^+$ and $A,B,C,a,b,c$ are constants s.t. $b^2 - 4c < 0$
The condition $b^2 - 4c < 0$ means that the quadratic polynomial $x^2 + bx + c$ cannot be factored into linear factors with real coefficients, or the quadratic equation $x^2 + bx + c = 0$ has no real roots. Such a quadratic factor is said to be irreducible. When a rational function has been so expressed, we say that it has been decomposed into partial functions. 

We shall not bother to prove that partial fraction decompositions always exist. Instead, we shall show by means of examples how to obtain the partial fractions in specific problems.

**Case 1** The denominator is a product of distinct linear factors

Suppose that $g(x)$ splits into $n$ distinct linear factors, say $g(x) = (x - x^1)(x-x^2)...(x-x^n)$

Notice that a linear combination of the form $\frac{A_1}{x - x_n} + ... + \frac{A_n}{x - x_n}$ may be expressed as a single fraction with common denominator $g(x)$, and the numerator of this fraction will be a polynomial of degree $< n$ involving the A's.
Therefore, if we can find A's to make this numerator equal to $f(x)$, we shall have the decomposition

$\frac{f(x)}{g(x)} = \frac{A_1}{x - x_n} + ... + \frac{A_n}{x - x_n}$

and $\int \frac{f(x)}{g(x)} = \sum_{i = 1}^n \log |x - x_i|$

**Case 2** The denominator is a product of linear factors, some of which are repeated.

If we have terms that are repeated, i.e. $g(x) = (x - 1)(x + 1)^2$, then we add all the primitive terms:

$\frac{f}{g} = \frac{A_1}{x - 1} + \frac{A_2}{x + 1} + \frac{A_3}{(x + 1)^2}$

Then after clearing the fractions, we get something like

$f(x) = A_1(x + 1)^2 + A_2(x-1)(x+1) + A_3(x - 1)$

In order to figure out $A_2$, we could use a convenient $x$ and get another equation, or we could differentiate to get a relation between a known (like $A_3$) and the unknown $A_2$

If a linear factor $x + a$ appears $p$ times in the denominator, then for this factor we must allow for a sum of $p$ terms, namely $\sum_{k = 1}^p \frac{A_k}{(x + a)^k}$ where the A's are constants. A sum of this type is to be used for each repeated linear factor.

**Case 3** The denominator contains irreducible quadratic factors, none of which are repeated

Suppose $g = (x^3 - 1) = (x-1)(x^2 + x + 1)$, where $x^2 + x + 1$ is irreducible.

Then we try a decomposition of the form $\frac{f}{g} = \frac{A}{x - 1} + \frac{Bx + C}{x^2 + x + 1}$

Then we solve for A, B, C as usual, and evaluate the integral like

$\int \frac{f}{g} = \int \frac{A}{x - 1} + \int \frac{Bx + C}{x^2 + x + 1}$

**Case 4** The denominator contains irreducible quadratic factors, some of which are repeated

This is similar to the cases above, except that for our repeated irreducible factors we expand them out into a sum of $m$ terms $\sum_{k = 1}^m \frac{B_k x + C_k}{(x^2 + bx + c)^k}$ where each numerator is linear.

**In General**

The problem of integrating a proper rational function reduces to that of calculating integrals of the forms

$\int \frac{dx}{(x + a)^n}$
$\int \frac{x dx}{(x^2 + bx + c)^m}$
$\int \frac{dx}{(x^2 + bx + c)^m}$

where the first integral is $\log |x + a|$ if $n = 1$ and $\frac{(x + a)^{1 - n}}{1 - n}$ if $n > 1$.

To treat the other two, we express the quadratic as a sum of two squares by writing

$x^2 + bx + c = (x + \frac{b}{2})^2 + (c - \frac{b^2}{4}) = u^2 + \alpha^2$ where $u = x + \frac{b}{2}$ and $\alpha = \frac{1}{2}\sqrt{4c - b^2}$ (this is possible because $4c - b^2 > 0$.

The substitution $u = x + b/2$ reduces the problem to that of computing

$\int \frac{u}{(u^2 + \alpha^2)^m}$ where if $m = 1$ is $\frac{1}{2}\log(u^2 + \alpha^2)$ and $\frac{\frac{1}{2}(u^2 + \alpha^2)^{1 - m}}{1 - m}$ if $m > 1$

$\int \frac{du}{(u^2 + \alpha^2)^m}$ where if $m = 1$ is $\frac{1}{\alpha} \arctan \frac{u}{\alpha} + C$, and if $m > 1$ can be reduced to the case $m = 1$ by repeated application of the recursion formula:

$\int \frac{du}{(u^2 + \alpha^2)^m} = \frac{1}{2 \alpha^2 (m - 1)} \frac{u}{(u^2 + \alpha^2)^{m - 1}} + \frac{2m - 3}{2 \alpha^2 (m - 1)} \int \frac{du}{(u^2 + \alpha^2)^{m - 1}}$

* Integrals which can be transformed into integrals of rational functions

$\int \frac{dx}{sinx + cosx} = \frac{\sqrt{2}}{2} \log |\frac{\tan \frac{x}{2} - 1 + \sqrt{2}}{\tan \frac{x}{2} - 1 - \sqrt{2}}| + C$

The trigonometric substitution $t = \arcsin x$ is good to try when an integral involves $\sqrt{1 - x^2}$.

More generally, any integral of the form $\int R(x, \sqrt{a^2 - x^2}) dx$, where $R$ is a rational function of 2 variables, can be transformed by the substitution

$x = a \sin t$ and $dx = a \cos t dt$

into an integral of the form $\int R(a \sin t, a \cos t) a \cos t dt$

The same method works for integrals of the form $\int R(x, \sqrt{a^2 - (cx + d)^2}) dx$ where we use the trigonometric substitution $cx + d = a \sin t$

We can deal similarly with integrals of the form $\int R(x, \sqrt{a^2 + (cx + d)^2}) dx$ by substituting $cx + d = a \tan t$, $c dx = a \sec^2 t dt$

For integrals of the form $\int R(x, \sqrt{(cx + d)^2 - a^2}) dx$, we use $cx + d = a \sec t$, $c dx = a \sec t \tan t dt$

In either case, the new integrand becomes a rational function of $\sin t$ and $\cos t$

* Exercises

$\arctan(x) + \arctan(y) = \arctan(\frac{x + y}{1 - xy})$

* Miscellaneous Review Exercises

  On Problem 1
