* Polynomial Approximations to Functions

  If the difference between a function and its polynomial approximation is sufficiently small, then we can, for practical purposes, compute with the polynomial in place of the original function.

  In this chapter, we shall be interested in obtaining a polynomial which agrees with f and some of its derivatives at a given point.

  We can approximate $e^x$ with tighter and tighter bounds with a polynomial which agrees with its first n terms about some point:

  $P(x) = \sum_{i = 0}^n \frac{x^i}{i!}$

* The Taylor Polynomials Generated by a Function

** Theorem 7.1 | Taylor Polynomials

   Let $f$ be a function with derivatives of order $n$ at the point $x = 0$. Then there exists one and only one polynomial $P$ of degree $\leq n$ which satisfies the $n + 1$ conditions

   $P(0) = f(0), P'(0) = f'(0), ..., P^{(n)}(0) = f^{(n)}(0)$

   This polynomial is given by the formula

   $P(x) = \sum_{k = 0}^{n} \frac{f^{(k)}(0)}{k!} x^k$

   In the same way, we may show that there is one and only one polynomial of degree $\leq n$ which agrees with $f$ and its first $n$ derivatives at a point $x = a$.

   $P(x) = \sum_{k = 0}^n \frac{f^{(k)}(a)}{k!} (x - a)^k$

   This is the one and only polynomial of degree $\leq n$ which satisfies the conditions

   $P(a) = f(a), P'(a) = f'(a), ..., P^{(n)}(a) = f^{(n)}(a)$

   and it is referred to as a **Taylor Polynomial**, or more precisely, the Taylor Polynomial of degree $n$ generated by $f$ at the point $a$.

   It is convenient to have a notation that indicates the dependence of the Taylor polynomial $P$ on $f$ and $n$. We shall indicate this by writing
   $P = T_n(f)$. The symbol $T_n$ is called the Taylor operator of degree $n$. When this operator is applied to a function, it produces a new function $T_n f$, the Taylor polynomial of degree $n$.
   The value of this function at $x$ is denoted by $T_n[f(x)]$ or $T_n f(x; a)$ if we wish to indicate the dependence on $a$.

* Calculus of Taylor Polynomials

  Sometimes the calculation of the derivatives $f^{(k)}(a)$ may become lengthy, so it is desirable to have alternative methods for determining Taylor polynomials.
  The next theorem describes properties of the Taylor operator that often enable us to obtain new Taylor polynomials from given ones.

** Theorem 7.2 | Properties of the Taylor Operator $T_n$

   a. **Linearity Property**: If $c_1, c_2$ are constants, then $T_n(c_1 f + c_2 g) = c_1 T_n(f) + c_2 T_n(g)$
   b. **Differentiation Property**: The derivative of a Taylor polynomial of $f$ is a Taylor polynomial of $f'$. In fact, we have $(T_n f)' = T_{n - 1}(f')$
   c. **Integration Property**: An indefinite integral of a Taylor polynomial of $f$ is a Taylor polynomial of an indefinite integral of $f$. More precisely, if $g(x) = \int_a^x f(t) dt$, then $T_{n + 1} g(x) = \int_a^x T_n f(t) dt$
    
** Theorem 7.3 | Substitution Property

   Let $g(x) = f(cx)$, where $c$ is a constant. Then we have
   $T_n g(x; a) = T_n f(cx; ca)$

   In particular, when $a = 0$, we have $T_n g(x) = T_n f(cx)$

** Theorem 7.4 | Taylor Polynomial Generated by $f$ at 0

   Let $P_n$ be a polynomial of degree $n \geq 1$. Let $f$ and $g$ be two functions with derivatives of order $n$ at 0 and assume that $f(x) = P_n(x) + x^n g(x)$, where $g(x) \to 0$ as $x \to 0$. Then $P_n$ is the Taylor polynomial generated by $f$ at 0.

** Exercises
   
#+BEGIN_SRC R
tibble("x" = seq(from = -5, 5, .01)) %>%
    mutate(y = funk(x),
           sin = sin(x),
           cos = cos(x),
           zero_pt = ifelse(between(y, -0.1, 0.1), TRUE, FALSE)) -> datum

datum %>%
    ggplot() +
    geom_hline(yintercept = 0, color = "gray") +
    geom_point(data = filter(datum, zero_pt), aes(x = x, y = 0), shape = 1) +
    geom_line(aes(x = x, y = (x - (x^3 / factorial(3)))), color = "lightblue") +
    geom_line(aes(x = x, y = (x - (x^3 / factorial(3)) + (x^5 / factorial(5)))), color = "forestgreen") +
    geom_line(aes(x = x, y = (x - (x^3 / factorial(3)) + (x^5 / factorial(5)) - (x^7 / factorial(7)))), color = "red") +
    geom_line(aes(x = x, y = (x - (x^3 / factorial(3)) + (x^5 / factorial(5)) - (x^7 / factorial(7)) + (x^9 / factorial(9)))), color = "orange") +
    geom_line(aes(x = x, y = sin), color = "mediumpurple") +
    ylab("Polynomial Approximations to sin(x)") +
    xlab("x")

datum %>%
    ggplot() +
    geom_hline(yintercept = 0, color = "gray") +
    geom_line(aes(x = x, y = (1 - (x^2 / factorial(2)))), color = "lightblue") +
    geom_line(aes(x = x, y = (1 - (x^2 / factorial(2)) + (x^4 / factorial(4)))), color = "forestgreen") +
    geom_line(aes(x = x, y = (1 - (x^2 / factorial(2)) + (x^4 / factorial(4)) - (x^6 / factorial(6)))), color = "red") +
    geom_line(aes(x = x, y = (1 - (x^2 / factorial(2)) + (x^4 / factorial(4)) - (x^6 / factorial(6)) + (x^8 / factorial(8)))), color = "orange") +
    geom_line(aes(x = x, y = cos), color = "mediumpurple") +
    ylab("Polynomial Approximations to cos(x)") +
    xlab("x")
#+END_SRC

* Taylor's Formula with Remainder

** Theorem 7.5 | Error Arising from Linear Approximation

   Assume $f$ has a continuous second derivative $f''$ in some neighborhood of $a$. Then, for every $x$ in this neighborhood, we have
   
   $f(x) = f(a) + f'(a)(x - a) + E_1(x)$

   where

   $E_1(x) = \int_a^x (x - t) f''(t) dt$

** Theorem 7.6 | Error Arising from a Polynomial Approximation of Degree n

   Assume $f$ has a continuous derivative of order $n + 1$ in some interval containing a. Then, for every $x$ in this interval, we have the Taylor formula

   $f(x) = \sum_{k = 0}^n \frac{f^{(k)}(a)}{k!}(x - a)^k + E_n(x)$

   where

   $E_n(x) = \frac{1}{n!} \int_a^x (x - t)^n f^{(n + 1)}(t) dt$

* Estimates for the Error in Taylor's Formula

** Theorem 7.7 | Bounds on $E_n(x)$

   If the $(n + 1)$ st derivative of $f$ satisfies the inequalities

   $m \leq f^{(n + 1)}(t) \leq M$

   for all $t$ in some interval containing $a$, then for every $x$ in this interval we have the following estimates:

   $m \frac{(x - a)^{n + 1}}{(n + 1)!} \leq E_n(x) \leq M \frac{(x - a)^{n + 1}}{(n + 1)!}$ if $x < a$

   and

   $m \frac{{(a - x)}^{n + 1}}{(n + 1)!} \leq (-1)^{n + 1} E_n (x) \leq M \frac{(a - x)^{n + 1}}{(n + 1)!}$ if $a > x$

   
   Polynomial approximations often enable us to obtain approximate numerical values for integrals that cannot be evaluated directly in terms of elementary functions.
   That is to say, $f$ cannot be obtained from polynomials, exponentials, logarithms, trigonometric or inverse trigonometric functions in a finite number of steps by using the operations of addition, subtraction, multiplication, division, or composition.

* Other Forms of the Remainder in Taylor's Formula
  
** Lagrange's Form

   Since $(x - t)^n$ never changes sign in the interval of integration, and since $f^{(n + 1)}$ is continuous on this interval, the weighted mean value theorem for integrals allows us to express the error remainder as

   $E_n(x) = \frac{f^{(n + 1)}(c)}{(n + 1)!} (x - a)^{(n + 1)}$

** Weaker Generalization
   
   We can drop the continuity requirement on $f^{(n + 1)}$ and derive Lagrange's form and other forms under a weaker hypothesis.

   Suppose $f^{(n + 1)}$ exists in some open interval $(h, k)$ containing the point $a$, and assume that $f^{(n)}$ is continuous in the closed interval $[h, k]$. Choose any $x \neq a \in [h, k]$. For simplicity, we can say $x > a$. Fix $x$ and define a new function as follows:

   $F(t) = f(t) + \sum\limits_{k = 1}^n \frac{f^{(k)}(t)}{k!}(x - t)^k$
   Taking the derivative

   $F'(t) = \frac{(x - t)^n}{n!} f^{(n + 1)}(t)$

   Let $G$ be any function that is continuous on $[a, x]$ and differentiable on $(a, x)$. Then we can apply Cauchy's mean value formula to write

   $G'(c)[F(x) - F(a)] = F'(c)[G(x) - G(a)]$

   for some $c \in (a, x)$. If $G' \neq 0$, this gives the following formula for the error

   $E_n(x) = \frac{F'(c)}{G'(c)}[G(x) - G(a)]$

   We can express the error in various forms for different choices of $G$.

   If we let $G(t) = (x - t)^{n + 1}$, we obtain Lagrange's form.

** Cauchy's Form

   If we let $G(t) = x - t$, we obtain Cauchy's form for the remainder:

   $E_n(x) = \frac{f^{(n + 1)}(c)}{n!}(x - c)^n (x - a)$ where $a < c < x$
   
** Another Form

   If we let $G(t) = (x - t)^p$, where $p \geq 1$, we obtain:

   $E_n(x) = \frac{f^{(n + 1)}(c)}{n! p} (x - c)^{n + 1 - p}(x - a)^p$ where $a < c < x$

* Further Remarks on the Error in Taylor's Formula. The $o$ - notation

** Definition | Little o notation

   Assume $g(x) \neq 0$ for all $x \neq a$ in some interval containing $a$.
   The notation $f(x) = o(g(x))$ as $x \to a$ means that
   $\lim\limits_{x \to a} \frac{f(x)}{g(x)} = 0$


   The symbol $f(x) = o(g(x))$ is read "$f(x)$ is little oh of $g(x)$", or $f(x)$ is of smaller order than $g(x)$, and is intended to convey the idea that for $x$ near $a$, $f(x)$ is small compared with $g(x)$.

** Taylor's Formula with $o$ notation

   $f(x) = \sum_{k = 0}^n \frac{f^{(k)}(a)}{k!} (x - a)^k + o((x - a)^n)$ as $x \to a$

** Theorem 7.8 | Algebra of $o$ symbols

   As $x \to a$, we have the following:

   a. $o(g(x)) \pm o(g(x)) = o(g(x))$
   b. $o(cg(x)) = o(g(x))$ if $c \neq 0$
   c. $f(x) \cdot o(g(x)) = o(f(x)g(x))$
   d. $o(o(g(x))) = o(g(x))$
   e. $\frac{1}{1 + g(x)} = 1 - g(x) + o(g(x))$ if $g(x) \to 0$ as $x \to a$

* Applications to Indeterminate Forms

  If we have a limit such that $\lim\limits_{x \to 0} \frac{a}{b} \to \frac{0}{0}$, we have an indeterminate form. Taylor's formula and the $o$ - notation enable us to calculate the limit of an indeterminate form simply by approximating the numerator as a polynomial.

* Exercises

  On exercise 18
